import Foundation

enum BISTStockList {

    static let all: [Stock] = [

        // MARK: - Bankacılık
        Stock(id: "ALBRK.IS", symbol: "ALBRK", name: "Albaraka Türk Katılım Bankası", sector: "Bankacılık"),
        Stock(id: "GARAN.IS", symbol: "GARAN", name: "Türkiye Garanti Bankası", sector: "Bankacılık"),
        Stock(id: "HALKB.IS", symbol: "HALKB", name: "Türkiye Halk Bankası", sector: "Bankacılık"),
        Stock(id: "ISBTR.IS", symbol: "ISBTR", name: "Türkiye İş Bankası", sector: "Bankacılık"),
        Stock(id: "ISCTR.IS", symbol: "ISCTR", name: "Türkiye İş Bankası", sector: "Bankacılık"),
        Stock(id: "ISKUR.IS", symbol: "ISKUR", name: "Türkiye İş Bankası", sector: "Bankacılık"),
        Stock(id: "KLNMA.IS", symbol: "KLNMA", name: "Türkiye Kalkınma Ve Yatırım Bankası", sector: "Bankacılık"),
        Stock(id: "TSKB.IS", symbol: "TSKB", name: "Türkiye Sınai Kalkınma Bankası", sector: "Bankacılık"),
        Stock(id: "VAKBN.IS", symbol: "VAKBN", name: "Türkiye Vakıflar Bankası", sector: "Bankacılık"),
        Stock(id: "YKBNK.IS", symbol: "YKBNK", name: "Yapı Ve Kredi Bankası", sector: "Bankacılık"),

        // MARK: - Çimento
        Stock(id: "AFYON.IS", symbol: "AFYON", name: "Afyon Çimento Sanayi", sector: "Çimento"),
        Stock(id: "AKCNS.IS", symbol: "AKCNS", name: "Akçansa Çimento", sector: "Çimento"),
        Stock(id: "BASCM.IS", symbol: "BASCM", name: "Baştaş Başkent Çimento", sector: "Çimento"),
        Stock(id: "BOBET.IS", symbol: "BOBET", name: "Boğaziçi Beton", sector: "Çimento"),
        Stock(id: "BSOKE.IS", symbol: "BSOKE", name: "Batısöke Söke Çimento Sanayii", sector: "Çimento"),
        Stock(id: "BTCIM.IS", symbol: "BTCIM", name: "Batıçim Batı Anadolu Çimento", sector: "Çimento"),
        Stock(id: "BUCIM.IS", symbol: "BUCIM", name: "Bursa Çimento Fabrikası", sector: "Çimento"),
        Stock(id: "CIMSA.IS", symbol: "CIMSA", name: "Çimsa Çimento", sector: "Çimento"),
        Stock(id: "CMBTN.IS", symbol: "CMBTN", name: "Çimbeton Hazırbeton Ve Prefabrik", sector: "Çimento"),
        Stock(id: "CMENT.IS", symbol: "CMENT", name: "Çimentaş İzmir Çimento Fabrikası", sector: "Çimento"),
        Stock(id: "GOLTS.IS", symbol: "GOLTS", name: "Göltaş Göller Bölgesi Çimento", sector: "Çimento"),
        Stock(id: "KONYA.IS", symbol: "KONYA", name: "Konya Çimento Sanayii", sector: "Çimento"),
        Stock(id: "NUHCM.IS", symbol: "NUHCM", name: "Nuh Çimento", sector: "Çimento"),
        Stock(id: "OYAKC.IS", symbol: "OYAKC", name: "Oyak Çimento Fabrikaları", sector: "Çimento"),

        // MARK: - Enerji
        Stock(id: "A1YEN.IS", symbol: "A1YEN", name: "A1 Yenilenebilir Enerji Uretim AS", sector: "Enerji"),
        Stock(id: "AHGAZ.IS", symbol: "AHGAZ", name: "Ahlatcı Doğal Gaz Dağıtım Enerji Ve", sector: "Enerji"),
        Stock(id: "AKENR.IS", symbol: "AKENR", name: "Akenerji Elektrik Üretim", sector: "Enerji"),
        Stock(id: "AKFYE.IS", symbol: "AKFYE", name: "Akfen Yenilenebilir Enerji", sector: "Enerji"),
        Stock(id: "AKSEN.IS", symbol: "AKSEN", name: "Aksa Enerji Üretim", sector: "Enerji"),
        Stock(id: "AKSUE.IS", symbol: "AKSUE", name: "Aksu Enerji", sector: "Enerji"),
        Stock(id: "ALFAS.IS", symbol: "ALFAS", name: "Alfa Solar Enerji", sector: "Enerji"),
        Stock(id: "ARASE.IS", symbol: "ARASE", name: "Doğu Aras Enerji Yatırımları", sector: "Enerji"),
        Stock(id: "ARFYE.IS", symbol: "ARFYE", name: "Arf Bio Yenilenebilir Enerji Uretim", sector: "Enerji"),
        Stock(id: "AYDEM.IS", symbol: "AYDEM", name: "Aydem Yenilenebilir Enerji", sector: "Enerji"),
        Stock(id: "AYEN.IS", symbol: "AYEN", name: "Ayen Enerji", sector: "Enerji"),
        Stock(id: "AYGAZ.IS", symbol: "AYGAZ", name: "Aygaz", sector: "Enerji"),
        Stock(id: "BASGZ.IS", symbol: "BASGZ", name: "Başkent Doğalgaz Dağıtım", sector: "Enerji"),
        Stock(id: "BESTE.IS", symbol: "BESTE", name: "Best Brands Grup Enerji Yatirim as", sector: "Enerji"),
        Stock(id: "BIGEN.IS", symbol: "BIGEN", name: "Birlesim Grup Enerji Yatirimlari AS", sector: "Enerji"),
        Stock(id: "BIOEN.IS", symbol: "BIOEN", name: "Biotrend Çevre Ve Enerji", sector: "Enerji"),
        Stock(id: "CANTE.IS", symbol: "CANTE", name: "Çan2 Termik", sector: "Enerji"),
        Stock(id: "CATES.IS", symbol: "CATES", name: "Cates Elektrik Uretim Anonim", sector: "Enerji"),
        Stock(id: "CONSE.IS", symbol: "CONSE", name: "Consus Enerji İşletmeciliği Ve", sector: "Enerji"),
        Stock(id: "ECOGR.IS", symbol: "ECOGR", name: "Ecogreen Enerji Holding", sector: "Enerji"),
        Stock(id: "ENERY.IS", symbol: "ENERY", name: "Enerya Enerji", sector: "Enerji"),
        Stock(id: "ENJSA.IS", symbol: "ENJSA", name: "Enerjisa Enerji", sector: "Enerji"),
        Stock(id: "ENTRA.IS", symbol: "ENTRA", name: "Ic Enterra Yenilenebilir Enerji AS", sector: "Enerji"),
        Stock(id: "ESEN.IS", symbol: "ESEN", name: "Esenboğa Elektrik Üretim", sector: "Enerji"),
        Stock(id: "GWIND.IS", symbol: "GWIND", name: "Galata Wınd Enerji", sector: "Enerji"),
        Stock(id: "HUNER.IS", symbol: "HUNER", name: "Hun Yenilenebilir Enerji Üretim", sector: "Enerji"),
        Stock(id: "IZENR.IS", symbol: "IZENR", name: "Izdemir Enerji Elektrik Uretim", sector: "Enerji"),
        Stock(id: "KCHOL.IS", symbol: "KCHOL", name: "Koç Holding", sector: "Enerji"),
        Stock(id: "KONTR.IS", symbol: "KONTR", name: "Kontrolmatik Teknoloji Enerji Ve", sector: "Enerji"),
        Stock(id: "MAGEN.IS", symbol: "MAGEN", name: "Margün Enerji Üretim", sector: "Enerji"),
        Stock(id: "MOGAN.IS", symbol: "MOGAN", name: "Mogan Enerji Yatirim Holding", sector: "Enerji"),
        Stock(id: "NTGAZ.IS", symbol: "NTGAZ", name: "Naturelgaz", sector: "Enerji"),
        Stock(id: "ODAS.IS", symbol: "ODAS", name: "Odaş Elektrik Üretim", sector: "Enerji"),
        Stock(id: "PAMEL.IS", symbol: "PAMEL", name: "Pamel Yenilenebilir Elektrik Üretim", sector: "Enerji"),
        Stock(id: "TATEN.IS", symbol: "TATEN", name: "Tatlipinar Enerji Uretim", sector: "Enerji"),
        Stock(id: "TRCAS.IS", symbol: "TRCAS", name: "Turcas Petrol", sector: "Enerji"),
        Stock(id: "TRENJ.IS", symbol: "TRENJ", name: "Tr Dogal Enerji Kaynaklari", sector: "Enerji"),
        Stock(id: "TUPRS.IS", symbol: "TUPRS", name: "Tüpraş-türkiye Petrol Rafinerileri", sector: "Enerji"),
        Stock(id: "YEOTK.IS", symbol: "YEOTK", name: "Yeo Teknoloji Enerji Ve Endüstri", sector: "Enerji"),
        Stock(id: "ZOREN.IS", symbol: "ZOREN", name: "Zorlu Enerji Elektrik Üretim", sector: "Enerji"),

        // MARK: - Finans
        Stock(id: "A1CAP.IS", symbol: "A1CAP", name: "A1 Capital Yatitim Menkul Degerler", sector: "Finans"),
        Stock(id: "AGESA.IS", symbol: "AGESA", name: "Agesa Hayat Ve Emeklilik", sector: "Finans"),
        Stock(id: "AKBNK.IS", symbol: "AKBNK", name: "Akbank", sector: "Finans"),
        Stock(id: "ANHYT.IS", symbol: "ANHYT", name: "Anadolu Hayat Emeklilik", sector: "Finans"),
        Stock(id: "ASGYO.IS", symbol: "ASGYO", name: "Asce Gayrımenkul Yatırım Ortaklıgı", sector: "Finans"),
        Stock(id: "BORLS.IS", symbol: "BORLS", name: "Borlease Otomotiv AS", sector: "Finans"),
        Stock(id: "BRKVY.IS", symbol: "BRKVY", name: "Birikim Varlık Yönetim", sector: "Finans"),
        Stock(id: "BULGS.IS", symbol: "BULGS", name: "Bulls Girisim Sermayesi Yatirim", sector: "Finans"),
        Stock(id: "CRDFA.IS", symbol: "CRDFA", name: "Credıtwest Faktoring", sector: "Finans"),
        Stock(id: "DSTKF.IS", symbol: "DSTKF", name: "Destek Faktoring", sector: "Finans"),
        Stock(id: "ENPRA.IS", symbol: "ENPRA", name: "Enpara Bank", sector: "Finans"),
        Stock(id: "ESCAR.IS", symbol: "ESCAR", name: "Escar Filo Kiralama Hizmetleri", sector: "Finans"),
        Stock(id: "ETYAT.IS", symbol: "ETYAT", name: "Euro Trend GYO", sector: "Finans"),
        Stock(id: "EUKYO.IS", symbol: "EUKYO", name: "Euro Kapital GYO", sector: "Finans"),
        Stock(id: "EUYO.IS", symbol: "EUYO", name: "Euro Menkul Kıymet GYO", sector: "Finans"),
        Stock(id: "GARFA.IS", symbol: "GARFA", name: "Garanti Faktoring", sector: "Finans"),
        Stock(id: "GEDIK.IS", symbol: "GEDIK", name: "Gedik Yatırım", sector: "Finans"),
        Stock(id: "GLBMD.IS", symbol: "GLBMD", name: "Global", sector: "Finans"),
        Stock(id: "GLCVY.IS", symbol: "GLCVY", name: "Gelecek Varlık Yönetimi", sector: "Finans"),
        Stock(id: "GOZDE.IS", symbol: "GOZDE", name: "Gözde Girişim Sermayesi GYO", sector: "Finans"),
        Stock(id: "GRNYO.IS", symbol: "GRNYO", name: "Garanti GYO", sector: "Finans"),
        Stock(id: "HDFGS.IS", symbol: "HDFGS", name: "Hedef Girişim Sermayesi GYO", sector: "Finans"),
        Stock(id: "HUBVC.IS", symbol: "HUBVC", name: "Hub Girişim Sermayesi GYO", sector: "Finans"),
        Stock(id: "ICBCT.IS", symbol: "ICBCT", name: "Icbc Turkey Bank", sector: "Finans"),
        Stock(id: "ICUGS.IS", symbol: "ICUGS", name: "Icu Girisim Sermayesi Yatirim", sector: "Finans"),
        Stock(id: "INFO.IS", symbol: "INFO", name: "İnfo Yatırım", sector: "Finans"),
        Stock(id: "ISFIN.IS", symbol: "ISFIN", name: "İş Finansal Kiralama", sector: "Finans"),
        Stock(id: "ISMEN.IS", symbol: "ISMEN", name: "İş Yatırım", sector: "Finans"),
        Stock(id: "KTLEV.IS", symbol: "KTLEV", name: "Katılımevım Tasarruf Fınansman", sector: "Finans"),
        Stock(id: "KUYAS.IS", symbol: "KUYAS", name: "Kuyaş Yatırım", sector: "Finans"),
        Stock(id: "LIDER.IS", symbol: "LIDER", name: "Ldr Turizm", sector: "Finans"),
        Stock(id: "LIDFA.IS", symbol: "LIDFA", name: "Lider Faktoring", sector: "Finans"),
        Stock(id: "OSMEN.IS", symbol: "OSMEN", name: "Osmanlı Yatırım", sector: "Finans"),
        Stock(id: "OYAYO.IS", symbol: "OYAYO", name: "Oyak GYO", sector: "Finans"),
        Stock(id: "OYYAT.IS", symbol: "OYYAT", name: "Oyak Yatırım", sector: "Finans"),
        Stock(id: "PRDGS.IS", symbol: "PRDGS", name: "Pardus Girişim Sermayesi GYO", sector: "Finans"),
        Stock(id: "QNBFK.IS", symbol: "QNBFK", name: "Qnb Finansal Kiralama", sector: "Finans"),
        Stock(id: "QNBTR.IS", symbol: "QNBTR", name: "Qnb Bank AS", sector: "Finans"),
        Stock(id: "SEKFK.IS", symbol: "SEKFK", name: "Şeker Finansal Kiralama", sector: "Finans"),
        Stock(id: "SKBNK.IS", symbol: "SKBNK", name: "Şekerbank", sector: "Finans"),
        Stock(id: "SKYMD.IS", symbol: "SKYMD", name: "Seker Yatirim Menkul Degerler", sector: "Finans"),
        Stock(id: "TERA.IS", symbol: "TERA", name: "Tera Yatırım", sector: "Finans"),
        Stock(id: "TUREX.IS", symbol: "TUREX", name: "Tureks Turizm Taşımacılık", sector: "Finans"),
        Stock(id: "ULUFA.IS", symbol: "ULUFA", name: "Ulusal Faktoring", sector: "Finans"),
        Stock(id: "VAKFA.IS", symbol: "VAKFA", name: "Vakıf Faktoring", sector: "Finans"),
        Stock(id: "VAKFN.IS", symbol: "VAKFN", name: "Vakıf Finansal Kiralama", sector: "Finans"),
        Stock(id: "VKFYO.IS", symbol: "VKFYO", name: "Vakıf Menkul Kıymet GYO", sector: "Finans"),

        // MARK: - Gıda
        Stock(id: "AEFES.IS", symbol: "AEFES", name: "Anadolu Efes Biracılık Ve Malt", sector: "Gıda"),
        Stock(id: "AGHOL.IS", symbol: "AGHOL", name: "AG Anadolu Grubu Holding", sector: "Gıda"),
        Stock(id: "AKHAN.IS", symbol: "AKHAN", name: "Akhan Un Fabrikasi Ve Tarim", sector: "Gıda"),
        Stock(id: "ALKLC.IS", symbol: "ALKLC", name: "Altinkilic Gida Ve Sut Sanayi", sector: "Gıda"),
        Stock(id: "ARMGD.IS", symbol: "ARMGD", name: "Armada Gida Ticaret Ve Sanayi", sector: "Gıda"),
        Stock(id: "ATAKP.IS", symbol: "ATAKP", name: "Atakey Patates Gida Sanayi Ve", sector: "Gıda"),
        Stock(id: "AVOD.IS", symbol: "AVOD", name: "A.v.o.d. Kurutulmuş Gıda Ve Tarım", sector: "Gıda"),
        Stock(id: "BALSU.IS", symbol: "BALSU", name: "Balsu Gida Sanayi Ve Ticaret Anonim", sector: "Gıda"),
        Stock(id: "BAYRK.IS", symbol: "BAYRK", name: "Bayrak Ebt Taban", sector: "Gıda"),
        Stock(id: "BESLR.IS", symbol: "BESLR", name: "Besler Gida Ve Kimya Sanayi Ve", sector: "Gıda"),
        Stock(id: "BLCYT.IS", symbol: "BLCYT", name: "Bilici Yatırım", sector: "Gıda"),
        Stock(id: "BOSSA.IS", symbol: "BOSSA", name: "Bossa Ticaret Ve Sanayi İşletmeleri", sector: "Gıda"),
        Stock(id: "BRKSN.IS", symbol: "BRKSN", name: "Berkosan Yalıtım Ve Tecrit", sector: "Gıda"),
        Stock(id: "CCOLA.IS", symbol: "CCOLA", name: "Coca-cola İçecek", sector: "Gıda"),
        Stock(id: "CEMZY.IS", symbol: "CEMZY", name: "Cem Zeytın", sector: "Gıda"),
        Stock(id: "DARDL.IS", symbol: "DARDL", name: "Dardanel Önentaş Gıda", sector: "Gıda"),
        Stock(id: "DERHL.IS", symbol: "DERHL", name: "Derlüks Yatırım Holding", sector: "Gıda"),
        Stock(id: "DESA.IS", symbol: "DESA", name: "Desa Deri", sector: "Gıda"),
        Stock(id: "DMRGD.IS", symbol: "DMRGD", name: "Dmr Unlu Mamuller Uretim Gida", sector: "Gıda"),
        Stock(id: "DNISI.IS", symbol: "DNISI", name: "Dinamik Isı Makina Yalıtım", sector: "Gıda"),
        Stock(id: "DUNYH.IS", symbol: "DUNYH", name: "Dunya Holding Anonim Sirketi", sector: "Gıda"),
        Stock(id: "DURKN.IS", symbol: "DURKN", name: "Durukan Sekerleme Sanayi Ve Ticaret", sector: "Gıda"),
        Stock(id: "DYOBY.IS", symbol: "DYOBY", name: "Dyo Boya Fabrikaları", sector: "Gıda"),
        Stock(id: "EFOR.IS", symbol: "EFOR", name: "Efor Yatirim Sanayi Ticaret", sector: "Gıda"),
        Stock(id: "EGPRO.IS", symbol: "EGPRO", name: "Ege Profil", sector: "Gıda"),
        Stock(id: "EKSUN.IS", symbol: "EKSUN", name: "Eksun Gıda Tarım", sector: "Gıda"),
        Stock(id: "ELITE.IS", symbol: "ELITE", name: "Elite Naturel Organik Gıda", sector: "Gıda"),
        Stock(id: "ENSRI.IS", symbol: "ENSRI", name: "Ensari Deri Gıda", sector: "Gıda"),
        Stock(id: "ERSU.IS", symbol: "ERSU", name: "Ersu Meyve Ve Gıda", sector: "Gıda"),
        Stock(id: "FADE.IS", symbol: "FADE", name: "Fade Gıda Yatırım", sector: "Gıda"),
        Stock(id: "FRIGO.IS", symbol: "FRIGO", name: "Frigo-pak Gıda Maddeleri", sector: "Gıda"),
        Stock(id: "GOKNR.IS", symbol: "GOKNR", name: "Göknur Gıda Maddeleri Enerji İmalat", sector: "Gıda"),
        Stock(id: "GUNDG.IS", symbol: "GUNDG", name: "Gundogdu Gida Sut Urunleri Sanayi", sector: "Gıda"),
        Stock(id: "HEKTS.IS", symbol: "HEKTS", name: "Hektaş Ticaret", sector: "Gıda"),
        Stock(id: "IZINV.IS", symbol: "IZINV", name: "İz Yatırım Holding", sector: "Gıda"),
        Stock(id: "KARTN.IS", symbol: "KARTN", name: "Kartonsan Karton", sector: "Gıda"),
        Stock(id: "KENT.IS", symbol: "KENT", name: "Kent Gıda Maddeleri Sanayii", sector: "Gıda"),
        Stock(id: "KLRHO.IS", symbol: "KLRHO", name: "Kiler Holding", sector: "Gıda"),
        Stock(id: "KNFRT.IS", symbol: "KNFRT", name: "Konfrut Gıda", sector: "Gıda"),
        Stock(id: "KOPOL.IS", symbol: "KOPOL", name: "Koza Polyester", sector: "Gıda"),
        Stock(id: "KRPLS.IS", symbol: "KRPLS", name: "Koroplast Temizlik Ambalaj Ürünleri", sector: "Gıda"),
        Stock(id: "KRSTL.IS", symbol: "KRSTL", name: "Kristal Kola Ve Meşrubat", sector: "Gıda"),
        Stock(id: "KRVGD.IS", symbol: "KRVGD", name: "Kervan Gıda", sector: "Gıda"),
        Stock(id: "KTSKR.IS", symbol: "KTSKR", name: "Kütahya Şeker Fabrikası", sector: "Gıda"),
        Stock(id: "LILAK.IS", symbol: "LILAK", name: "Lila Kagit Sanayi Ve Ticaret Anonim", sector: "Gıda"),
        Stock(id: "LRSHO.IS", symbol: "LRSHO", name: "Loras Holding Anonim Sirketi", sector: "Gıda"),
        Stock(id: "LUKSK.IS", symbol: "LUKSK", name: "Lüks Kadife Ticaret Ve Sanayii", sector: "Gıda"),
        Stock(id: "LYDYE.IS", symbol: "LYDYE", name: "Lydia Yesil Enerji Kaynaklari", sector: "Gıda"),
        Stock(id: "MEGAP.IS", symbol: "MEGAP", name: "Mega Polietilen Köpük", sector: "Gıda"),
        Stock(id: "MERKO.IS", symbol: "MERKO", name: "Merko Gıda", sector: "Gıda"),
        Stock(id: "METRO.IS", symbol: "METRO", name: "Metro Ticari Ve Mali Yatırımlar", sector: "Gıda"),
        Stock(id: "MEYSU.IS", symbol: "MEYSU", name: "Meysu Gida Sanayi", sector: "Gıda"),
        Stock(id: "OBAMS.IS", symbol: "OBAMS", name: "Oba Makarnacilik Sanayi Ve Ticaret", sector: "Gıda"),
        Stock(id: "OFSYM.IS", symbol: "OFSYM", name: "Ofis Yem Gida Sanayi", sector: "Gıda"),
        Stock(id: "ORCAY.IS", symbol: "ORCAY", name: "Orçay Ortaköy Çay", sector: "Gıda"),
        Stock(id: "OYLUM.IS", symbol: "OYLUM", name: "Oylum Sınai Yatırımlar", sector: "Gıda"),
        Stock(id: "OZRDN.IS", symbol: "OZRDN", name: "Özerden Plastik", sector: "Gıda"),
        Stock(id: "PENGD.IS", symbol: "PENGD", name: "Penguen Gıda", sector: "Gıda"),
        Stock(id: "PETUN.IS", symbol: "PETUN", name: "Pınar Entegre Et Ve Un Sanayii", sector: "Gıda"),
        Stock(id: "PINSU.IS", symbol: "PINSU", name: "Pınar Su Ve İçecek", sector: "Gıda"),
        Stock(id: "PNSUT.IS", symbol: "PNSUT", name: "Pınar Süt Mamulleri Sanayii", sector: "Gıda"),
        Stock(id: "POLTK.IS", symbol: "POLTK", name: "Politeknik Metal", sector: "Gıda"),
        Stock(id: "PSDTC.IS", symbol: "PSDTC", name: "Pergamon Status Dış", sector: "Gıda"),
        Stock(id: "RUZYE.IS", symbol: "RUZYE", name: "Ruzy Madencilik Ve Enerji", sector: "Gıda"),
        Stock(id: "SANFM.IS", symbol: "SANFM", name: "Sanifoam Endüstri Ve Tüketim", sector: "Gıda"),
        Stock(id: "SEGMN.IS", symbol: "SEGMN", name: "Segmen Kardesler Gida Uretim Ve", sector: "Gıda"),
        Stock(id: "SELVA.IS", symbol: "SELVA", name: "Selva Gıda", sector: "Gıda"),
        Stock(id: "SOKE.IS", symbol: "SOKE", name: "Söke Değirmencilik", sector: "Gıda"),
        Stock(id: "TARKM.IS", symbol: "TARKM", name: "Tarkim Bitki Koruma Sanayi", sector: "Gıda"),
        Stock(id: "TATGD.IS", symbol: "TATGD", name: "Tat Gıda", sector: "Gıda"),
        Stock(id: "TBORG.IS", symbol: "TBORG", name: "Türk Tuborg Bira Ve Malt Sanayii", sector: "Gıda"),
        Stock(id: "TEZOL.IS", symbol: "TEZOL", name: "Europap Tezol Kağıt", sector: "Gıda"),
        Stock(id: "TUKAS.IS", symbol: "TUKAS", name: "Tukaş Gıda", sector: "Gıda"),
        Stock(id: "ULKER.IS", symbol: "ULKER", name: "Ülker Bisküvi", sector: "Gıda"),
        Stock(id: "ULUUN.IS", symbol: "ULUUN", name: "Ulusoy Un", sector: "Gıda"),
        Stock(id: "VKING.IS", symbol: "VKING", name: "Viking Kağıt Ve Selüloz", sector: "Gıda"),
        Stock(id: "YAPRK.IS", symbol: "YAPRK", name: "Yaprak Süt Ve Besi Çiftlikleri", sector: "Gıda"),
        Stock(id: "YUNSA.IS", symbol: "YUNSA", name: "Yünsa Yünlü", sector: "Gıda"),
        Stock(id: "YYLGD.IS", symbol: "YYLGD", name: "Yayla Agro Gıda", sector: "Gıda"),

        // MARK: - GYO
        Stock(id: "AAGYO.IS", symbol: "AAGYO", name: "Agaoglu Avrasya Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "ADESE.IS", symbol: "ADESE", name: "Adese GYO", sector: "GYO"),
        Stock(id: "ADGYO.IS", symbol: "ADGYO", name: "Adra Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "AGYO.IS", symbol: "AGYO", name: "Atakule Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "AHSGY.IS", symbol: "AHSGY", name: "Ahes Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "AKFGY.IS", symbol: "AKFGY", name: "Akfen Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "AKMGY.IS", symbol: "AKMGY", name: "Akmerkez Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "AKSGY.IS", symbol: "AKSGY", name: "Akiş Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "ALGYO.IS", symbol: "ALGYO", name: "Alarko Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "ATAGY.IS", symbol: "ATAGY", name: "Ata Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "AVGYO.IS", symbol: "AVGYO", name: "Avrasya Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "AVPGY.IS", symbol: "AVPGY", name: "Avrupakent Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "BEGYO.IS", symbol: "BEGYO", name: "Bati Ege Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "DAPGM.IS", symbol: "DAPGM", name: "Dap", sector: "GYO"),
        Stock(id: "DGGYO.IS", symbol: "DGGYO", name: "Doğuş Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "DZGYO.IS", symbol: "DZGYO", name: "Deniz Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "EDIP.IS", symbol: "EDIP", name: "Edip GYO", sector: "GYO"),
        Stock(id: "EGEGY.IS", symbol: "EGEGY", name: "Egeyapi Avrupa Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "EKGYO.IS", symbol: "EKGYO", name: "Emlak Konut Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "EYGYO.IS", symbol: "EYGYO", name: "Eyg Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "HLGYO.IS", symbol: "HLGYO", name: "Halk Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "IDGYO.IS", symbol: "IDGYO", name: "İdealist Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "IHLGM.IS", symbol: "IHLGM", name: "İhlas Gayrimenkul Proje Geliştirme", sector: "GYO"),
        Stock(id: "ISGYO.IS", symbol: "ISGYO", name: "İş Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "KGYO.IS", symbol: "KGYO", name: "Koray Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "KLGYO.IS", symbol: "KLGYO", name: "Kiler Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "KRGYO.IS", symbol: "KRGYO", name: "Körfez Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "KZBGY.IS", symbol: "KZBGY", name: "Kızılbük Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "KZGYO.IS", symbol: "KZGYO", name: "Kuzugrup Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "LXGYO.IS", symbol: "LXGYO", name: "Luxera Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "MHRGY.IS", symbol: "MHRGY", name: "Mhr Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "MRGYO.IS", symbol: "MRGYO", name: "Martı Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "MSGYO.IS", symbol: "MSGYO", name: "Mistral Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "NUGYO.IS", symbol: "NUGYO", name: "Nurol Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "OZGYO.IS", symbol: "OZGYO", name: "Özderici Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "OZKGY.IS", symbol: "OZKGY", name: "Özak Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "PAGYO.IS", symbol: "PAGYO", name: "Panora Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "PEKGY.IS", symbol: "PEKGY", name: "Peker Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "PSGYO.IS", symbol: "PSGYO", name: "Pasifik Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "RGYAS.IS", symbol: "RGYAS", name: "Rönesans GYO", sector: "GYO"),
        Stock(id: "RYGYO.IS", symbol: "RYGYO", name: "Reysaş Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "SEGYO.IS", symbol: "SEGYO", name: "Şeker Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "SNGYO.IS", symbol: "SNGYO", name: "Sinpaş Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "SRVGY.IS", symbol: "SRVGY", name: "Servet Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "SURGY.IS", symbol: "SURGY", name: "Sur Tatil Evleri Gayrimenkul", sector: "GYO"),
        Stock(id: "SVGYO.IS", symbol: "SVGYO", name: "Savur Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "TDGYO.IS", symbol: "TDGYO", name: "Trend Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "TRGYO.IS", symbol: "TRGYO", name: "Torunlar Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "TSGYO.IS", symbol: "TSGYO", name: "Tskb Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "TURGG.IS", symbol: "TURGG", name: "Türker Proje Gayrimenkul Ve Yatırım", sector: "GYO"),
        Stock(id: "UFUK.IS", symbol: "UFUK", name: "Ufuk Yatırım Yönetim Ve Gayrimenkul", sector: "GYO"),
        Stock(id: "VKGYO.IS", symbol: "VKGYO", name: "Vakıf Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "VRGYO.IS", symbol: "VRGYO", name: "Vera Konsept Gayrimenkul Yatirim", sector: "GYO"),
        Stock(id: "YGGYO.IS", symbol: "YGGYO", name: "Yeni Gimat Gayrimenkul GYO", sector: "GYO"),
        Stock(id: "ZERGY.IS", symbol: "ZERGY", name: "Zeray Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "ZGYO.IS", symbol: "ZGYO", name: "Z Gayrimenkul Yatirim Ortakligi", sector: "GYO"),
        Stock(id: "ZRGYO.IS", symbol: "ZRGYO", name: "Ziraat Gayrimenkul GYO", sector: "GYO"),

        // MARK: - Hizmetler
        Stock(id: "AKYHO.IS", symbol: "AKYHO", name: "Akdeniz Yatırım Holding", sector: "Hizmetler"),
        Stock(id: "BINBN.IS", symbol: "BINBN", name: "Bin Ulasim Ve Akilli Sehir", sector: "Hizmetler"),
        Stock(id: "EDATA.IS", symbol: "EDATA", name: "E-data Teknoloji Pazarlama", sector: "Hizmetler"),
        Stock(id: "GATEG.IS", symbol: "GATEG", name: "Gate Group Teknoloji Medya Ve Siber", sector: "Hizmetler"),
        Stock(id: "IHAAS.IS", symbol: "IHAAS", name: "İhlas Haber Ajansı", sector: "Hizmetler"),
        Stock(id: "MACKO.IS", symbol: "MACKO", name: "Mackolik İnternet Hizmetleri", sector: "Hizmetler"),
        Stock(id: "MCARD.IS", symbol: "MCARD", name: "Metropal Kurumsal Hizmetler", sector: "Hizmetler"),
        Stock(id: "PCILT.IS", symbol: "PCILT", name: "Pc İletişim Ve Medya Hizmetleri", sector: "Hizmetler"),
        Stock(id: "PKART.IS", symbol: "PKART", name: "Plastikkart Akıllı Kart İletişim", sector: "Hizmetler"),
        Stock(id: "PRZMA.IS", symbol: "PRZMA", name: "Prizma Pres Matbaacılık Yayıncılık", sector: "Hizmetler"),
        Stock(id: "SAMAT.IS", symbol: "SAMAT", name: "Saray Matbaacılık Kağıtçılık", sector: "Hizmetler"),
        Stock(id: "SKYLP.IS", symbol: "SKYLP", name: "Skyalp Finansal Teknolojiler Ve", sector: "Hizmetler"),
        Stock(id: "SMRVA.IS", symbol: "SMRVA", name: "Sumer Varlik Yonetim", sector: "Hizmetler"),

        // MARK: - Holding
        Stock(id: "ALARK.IS", symbol: "ALARK", name: "Alarko Holding", sector: "Holding"),
        Stock(id: "DENGE.IS", symbol: "DENGE", name: "Denge Yatırım Holding", sector: "Holding"),
        Stock(id: "ECZYT.IS", symbol: "ECZYT", name: "Eczacıbaşı Yatırım Holding", sector: "Holding"),
        Stock(id: "ENDAE.IS", symbol: "ENDAE", name: "Enda Enerji Holding Anonim Sirketi", sector: "Holding"),
        Stock(id: "EUHOL.IS", symbol: "EUHOL", name: "Euro Yatırım Holding", sector: "Holding"),
        Stock(id: "GLRYH.IS", symbol: "GLRYH", name: "Güler Yatırım Holding", sector: "Holding"),
        Stock(id: "GLYHO.IS", symbol: "GLYHO", name: "Global Yatırım Holding", sector: "Holding"),
        Stock(id: "HEDEF.IS", symbol: "HEDEF", name: "Hedef Holding", sector: "Holding"),
        Stock(id: "IHLAS.IS", symbol: "IHLAS", name: "İhlas Holding", sector: "Holding"),
        Stock(id: "INVEO.IS", symbol: "INVEO", name: "Inveo Yatırım Holding", sector: "Holding"),
        Stock(id: "INVES.IS", symbol: "INVES", name: "Investco Holding", sector: "Holding"),
        Stock(id: "MARMR.IS", symbol: "MARMR", name: "Marmara Holding AS", sector: "Holding"),
        Stock(id: "SAHOL.IS", symbol: "SAHOL", name: "Hacı Ömer Sabancı Holding", sector: "Holding"),
        Stock(id: "TEHOL.IS", symbol: "TEHOL", name: "Tera Yatirim Teknoloji Holding", sector: "Holding"),
        Stock(id: "TRHOL.IS", symbol: "TRHOL", name: "Tera Financial Investments Holding", sector: "Holding"),
        Stock(id: "UNLU.IS", symbol: "UNLU", name: "Ünlü Yatırım Holding", sector: "Holding"),
        Stock(id: "VERUS.IS", symbol: "VERUS", name: "Verusa Holding", sector: "Holding"),

        // MARK: - İnşaat
        Stock(id: "AKFIS.IS", symbol: "AKFIS", name: "Akfen İnsaat Turizm Ve Ticaret AS", sector: "İnşaat"),
        Stock(id: "ANELE.IS", symbol: "ANELE", name: "Anel Elektrik Proje Taahhüt", sector: "İnşaat"),
        Stock(id: "ENKAI.IS", symbol: "ENKAI", name: "Enka İnşaat Ve", sector: "İnşaat"),
        Stock(id: "GLRMK.IS", symbol: "GLRMK", name: "Gulermak Agir Sanayi Insaat Ve", sector: "İnşaat"),
        Stock(id: "NATEN.IS", symbol: "NATEN", name: "Naturel Yenilenebilir Enerji", sector: "İnşaat"),
        Stock(id: "NIBAS.IS", symbol: "NIBAS", name: "Niğbaş Niğde Beton", sector: "İnşaat"),
        Stock(id: "ORGE.IS", symbol: "ORGE", name: "Orge Enerji Elektrik Taahhüt", sector: "İnşaat"),
        Stock(id: "RALYH.IS", symbol: "RALYH", name: "Ral Yatırım Holding", sector: "İnşaat"),
        Stock(id: "TKFEN.IS", symbol: "TKFEN", name: "Tekfen Holding", sector: "İnşaat"),
        Stock(id: "UCAYM.IS", symbol: "UCAYM", name: "Ucay Muhendislik Enerji Ve", sector: "İnşaat"),
        Stock(id: "YAYLA.IS", symbol: "YAYLA", name: "Yayla Enerji Üretim Turizm Ve", sector: "İnşaat"),
        Stock(id: "YYAPI.IS", symbol: "YYAPI", name: "Yeşil Yapı Endüstrisi", sector: "İnşaat"),

        // MARK: - Kağıt
        Stock(id: "ACSEL.IS", symbol: "ACSEL", name: "Acıselsan Acıpayam Selüloz", sector: "Kağıt"),
        Stock(id: "ALKA.IS", symbol: "ALKA", name: "Alkim Kağıt", sector: "Kağıt"),
        Stock(id: "BAKAB.IS", symbol: "BAKAB", name: "Bak Ambalaj", sector: "Kağıt"),
        Stock(id: "BARMA.IS", symbol: "BARMA", name: "Barem Ambalaj", sector: "Kağıt"),
        Stock(id: "BNTAS.IS", symbol: "BNTAS", name: "Bantaş Bandırma Ambalaj", sector: "Kağıt"),
        Stock(id: "DURDO.IS", symbol: "DURDO", name: "Duran Doğan Basım Ve Ambalaj", sector: "Kağıt"),
        Stock(id: "EMNIS.IS", symbol: "EMNIS", name: "Eminiş Ambalaj", sector: "Kağıt"),
        Stock(id: "GEDZA.IS", symbol: "GEDZA", name: "Gediz Ambalaj", sector: "Kağıt"),
        Stock(id: "KAPLM.IS", symbol: "KAPLM", name: "Kaplamin Ambalaj", sector: "Kağıt"),
        Stock(id: "KONKA.IS", symbol: "KONKA", name: "Konya Kağıt", sector: "Kağıt"),
        Stock(id: "MNDTR.IS", symbol: "MNDTR", name: "Mondi Turkey Oluklu Mukavva Kağıt", sector: "Kağıt"),
        Stock(id: "SEKUR.IS", symbol: "SEKUR", name: "Sekuro Plastik Ambalaj", sector: "Kağıt"),

        // MARK: - Kimya
        Stock(id: "AKSA.IS", symbol: "AKSA", name: "Aksa Akrilik Kimya Sanayii", sector: "Kimya"),
        Stock(id: "ALKIM.IS", symbol: "ALKIM", name: "Alkim Alkali Kimya", sector: "Kimya"),
        Stock(id: "BAHKM.IS", symbol: "BAHKM", name: "Bahadir Kimya Sanayi Ve Ticaret", sector: "Kimya"),
        Stock(id: "EKIZ.IS", symbol: "EKIZ", name: "Ekiz Kimya", sector: "Kimya"),
        Stock(id: "GENKM.IS", symbol: "GENKM", name: "Gentas Kimya Sanayi Ve Ticaret", sector: "Kimya"),
        Stock(id: "KLKIM.IS", symbol: "KLKIM", name: "Kalekim Kimyevi Maddeler", sector: "Kimya"),
        Stock(id: "MERCN.IS", symbol: "MERCN", name: "Mercan Kimya", sector: "Kimya"),
        Stock(id: "PETKM.IS", symbol: "PETKM", name: "Petkim Petrokimya Holding", sector: "Kimya"),
        Stock(id: "TMPOL.IS", symbol: "TMPOL", name: "Temapol Polimer Plastik Ve İnşaat", sector: "Kimya"),

        // MARK: - Lojistik
        Stock(id: "CLEBI.IS", symbol: "CLEBI", name: "Çelebi Hava Servisi", sector: "Lojistik"),
        Stock(id: "GSDDE.IS", symbol: "GSDDE", name: "Gsd Denizcilik Gayrimenkul İnşaat", sector: "Lojistik"),
        Stock(id: "GSDHO.IS", symbol: "GSDHO", name: "Gsd Holding", sector: "Lojistik"),
        Stock(id: "HOROZ.IS", symbol: "HOROZ", name: "Horoz Lojistik Kargo Hizmetleri Ve", sector: "Lojistik"),
        Stock(id: "HRKET.IS", symbol: "HRKET", name: "Hareket Proje Tasimaciligi Ve Yuk", sector: "Lojistik"),
        Stock(id: "MMCAS.IS", symbol: "MMCAS", name: "Mmc Sanayi Ve Ticari Yatırımlar", sector: "Lojistik"),
        Stock(id: "PASEU.IS", symbol: "PASEU", name: "Pasifik Eurasia Lojistik Dis", sector: "Lojistik"),
        Stock(id: "PGSUS.IS", symbol: "PGSUS", name: "Pegasus Hava Taşımacılığı", sector: "Lojistik"),
        Stock(id: "PLTUR.IS", symbol: "PLTUR", name: "Platform Turizm Taşımacılık Gıda", sector: "Lojistik"),
        Stock(id: "RYSAS.IS", symbol: "RYSAS", name: "Reysaş Taşımacılık Ve Lojistik", sector: "Lojistik"),
        Stock(id: "TAVHL.IS", symbol: "TAVHL", name: "Tav Havalimanları Holding", sector: "Lojistik"),
        Stock(id: "THYAO.IS", symbol: "THYAO", name: "Türk Hava Yolları A.o.", sector: "Lojistik"),
        Stock(id: "TLMAN.IS", symbol: "TLMAN", name: "Trabzon Liman İşletmeciliği", sector: "Lojistik"),

        // MARK: - Madencilik
        Stock(id: "CVKMD.IS", symbol: "CVKMD", name: "Cvk Maden İşletmeleri", sector: "Madencilik"),
        Stock(id: "MARBL.IS", symbol: "MARBL", name: "Tureks Turunc Madencilik Ic Ve Dis", sector: "Madencilik"),
        Stock(id: "PRKME.IS", symbol: "PRKME", name: "Park Elektrik Üretim Madencilik", sector: "Madencilik"),
        Stock(id: "TRMET.IS", symbol: "TRMET", name: "Tr Anadolu Metal Madencilik", sector: "Madencilik"),
        Stock(id: "VSNMD.IS", symbol: "VSNMD", name: "Visne Madencilik Uretim Sanayi Ve", sector: "Madencilik"),

        // MARK: - Metal
        Stock(id: "AYES.IS", symbol: "AYES", name: "Ayes Çelik Hasır Ve Çit", sector: "Metal"),
        Stock(id: "BMSCH.IS", symbol: "BMSCH", name: "Bms Çelik Hasır", sector: "Metal"),
        Stock(id: "BMSTL.IS", symbol: "BMSTL", name: "Bms Birleşik Metal", sector: "Metal"),
        Stock(id: "BRSAN.IS", symbol: "BRSAN", name: "Borusan Mannesmann Boru", sector: "Metal"),
        Stock(id: "BURCE.IS", symbol: "BURCE", name: "Burçelik Bursa Çelik Döküm Sanayii", sector: "Metal"),
        Stock(id: "BURVA.IS", symbol: "BURVA", name: "Burçelik Vana", sector: "Metal"),
        Stock(id: "CELHA.IS", symbol: "CELHA", name: "Çelik Halat Ve Tel Sanayii", sector: "Metal"),
        Stock(id: "CEMTS.IS", symbol: "CEMTS", name: "Çemtaş Çelik Makina", sector: "Metal"),
        Stock(id: "CUSAN.IS", symbol: "CUSAN", name: "Çuhadaroğlu Metal Sanayi Ve", sector: "Metal"),
        Stock(id: "DOGUB.IS", symbol: "DOGUB", name: "Doğusan Boru Sanayii", sector: "Metal"),
        Stock(id: "ERBOS.IS", symbol: "ERBOS", name: "Erbosan Erciyas Boru Sanayii", sector: "Metal"),
        Stock(id: "ERCB.IS", symbol: "ERCB", name: "Erciyas Çelik Boru", sector: "Metal"),
        Stock(id: "EREGL.IS", symbol: "EREGL", name: "Ereğli Demir Ve Çelik Fabrikaları", sector: "Metal"),
        Stock(id: "FORMT.IS", symbol: "FORMT", name: "Formet Metal Ve Cam", sector: "Metal"),
        Stock(id: "FRMPL.IS", symbol: "FRMPL", name: "Formul Plastik Ve Metal Sanayi AS", sector: "Metal"),
        Stock(id: "ISDMR.IS", symbol: "ISDMR", name: "İskenderun Demir Ve Çelik", sector: "Metal"),
        Stock(id: "IZMDC.IS", symbol: "IZMDC", name: "İzmir Demir Çelik", sector: "Metal"),
        Stock(id: "KCAER.IS", symbol: "KCAER", name: "Kocaer Çelik", sector: "Metal"),
        Stock(id: "KOCMT.IS", symbol: "KOCMT", name: "Koc Metalurji AS", sector: "Metal"),
        Stock(id: "KRDMA.IS", symbol: "KRDMA", name: "Kardemir Karabük Demir Çelik", sector: "Metal"),
        Stock(id: "KRDMB.IS", symbol: "KRDMB", name: "Kardemir Karabük Demir Çelik", sector: "Metal"),
        Stock(id: "KRDMD.IS", symbol: "KRDMD", name: "Kardemir Karabük Demir Çelik", sector: "Metal"),
        Stock(id: "MEGMT.IS", symbol: "MEGMT", name: "Mega Metal Sanayi", sector: "Metal"),
        Stock(id: "TCKRC.IS", symbol: "TCKRC", name: "Kirac Galvaniz Telekominikasyon", sector: "Metal"),
        Stock(id: "TUCLK.IS", symbol: "TUCLK", name: "Tuğçelik Alüminyum Ve Metal", sector: "Metal"),

        // MARK: - Otomotiv
        Stock(id: "BFREN.IS", symbol: "BFREN", name: "Bosch Fren Sistemleri", sector: "Otomotiv"),
        Stock(id: "FMIZP.IS", symbol: "FMIZP", name: "Federal-mogul İzmit Piston Ve Pim", sector: "Otomotiv"),
        Stock(id: "KARSN.IS", symbol: "KARSN", name: "Karsan Otomotiv Sanayii", sector: "Otomotiv"),

        // MARK: - Perakende
        Stock(id: "ARENA.IS", symbol: "ARENA", name: "Arena Bilgisayar", sector: "Perakende"),
        Stock(id: "ARTMS.IS", symbol: "ARTMS", name: "Artemis Hali A. S.", sector: "Perakende"),
        Stock(id: "ARZUM.IS", symbol: "ARZUM", name: "Arzum Elektrikli Ev Aletleri", sector: "Perakende"),
        Stock(id: "AZTEK.IS", symbol: "AZTEK", name: "Aztek Teknoloji Ürünleri", sector: "Perakende"),
        Stock(id: "BEYAZ.IS", symbol: "BEYAZ", name: "Beyaz Filo Oto Kiralama", sector: "Perakende"),
        Stock(id: "BIMAS.IS", symbol: "BIMAS", name: "Bim Birleşik Mağazalar", sector: "Perakende"),
        Stock(id: "BIZIM.IS", symbol: "BIZIM", name: "Bizim Toptan Satış Mağazaları", sector: "Perakende"),
        Stock(id: "CASA.IS", symbol: "CASA", name: "Casa Emtia Petrol Kimyevi Ve", sector: "Perakende"),
        Stock(id: "COSMO.IS", symbol: "COSMO", name: "Cosmos Yatırım Holding", sector: "Perakende"),
        Stock(id: "CRFSA.IS", symbol: "CRFSA", name: "Carrefoursa Carrefour Sabancı", sector: "Perakende"),
        Stock(id: "DCTTR.IS", symbol: "DCTTR", name: "Dct Trading Dis Ticaret Anonim", sector: "Perakende"),
        Stock(id: "DESPC.IS", symbol: "DESPC", name: "Despec Bilgisayar Pazarlama", sector: "Perakende"),
        Stock(id: "DGATE.IS", symbol: "DGATE", name: "Datagate Bilgisayar Malzemeleri", sector: "Perakende"),
        Stock(id: "DOAS.IS", symbol: "DOAS", name: "Doğuş Otomotiv Servis", sector: "Perakende"),
        Stock(id: "DOHOL.IS", symbol: "DOHOL", name: "Doğan Şirketler Grubu Holding", sector: "Perakende"),
        Stock(id: "EBEBK.IS", symbol: "EBEBK", name: "Ebebek Magazacılık", sector: "Perakende"),
        Stock(id: "GMTAS.IS", symbol: "GMTAS", name: "Gimat Mağazacılık", sector: "Perakende"),
        Stock(id: "GRTHO.IS", symbol: "GRTHO", name: "Grainturk Holding", sector: "Perakende"),
        Stock(id: "INDES.IS", symbol: "INDES", name: "İndeks Bilgisayar Sistemleri", sector: "Perakende"),
        Stock(id: "INGRM.IS", symbol: "INGRM", name: "Ingram Micro Bilişim Sistemleri", sector: "Perakende"),
        Stock(id: "KIMMR.IS", symbol: "KIMMR", name: "Ersan Alışveriş Hizmetleri Ve Gıda", sector: "Perakende"),
        Stock(id: "LYDHO.IS", symbol: "LYDHO", name: "Lydia Holding", sector: "Perakende"),
        Stock(id: "MARKA.IS", symbol: "MARKA", name: "Marka Yatırım Holding", sector: "Perakende"),
        Stock(id: "MEPET.IS", symbol: "MEPET", name: "Mepet Metro Petrol Ve Tesisleri", sector: "Perakende"),
        Stock(id: "MGROS.IS", symbol: "MGROS", name: "Migros", sector: "Perakende"),
        Stock(id: "MOBTL.IS", symbol: "MOBTL", name: "Mobiltel İletişim Hizmetleri", sector: "Perakende"),
        Stock(id: "MOPAS.IS", symbol: "MOPAS", name: "Mopas Marketcilik Gida Sanayi", sector: "Perakende"),
        Stock(id: "PENTA.IS", symbol: "PENTA", name: "Penta Teknoloji Ürünleri Dağıtım", sector: "Perakende"),
        Stock(id: "SELEC.IS", symbol: "SELEC", name: "Selçuk Ecza Deposu", sector: "Perakende"),
        Stock(id: "SOKM.IS", symbol: "SOKM", name: "Şok Marketler", sector: "Perakende"),
        Stock(id: "SUWEN.IS", symbol: "SUWEN", name: "Suwen Tekstil Sanayi Pazarlama", sector: "Perakende"),
        Stock(id: "TGSAS.IS", symbol: "TGSAS", name: "Tgs Dış", sector: "Perakende"),
        Stock(id: "TKNSA.IS", symbol: "TKNSA", name: "Teknosa İç Ve Dış", sector: "Perakende"),
        Stock(id: "VANGD.IS", symbol: "VANGD", name: "Vanet Gıda Sanayi İç Ve Dış", sector: "Perakende"),
        Stock(id: "YATAS.IS", symbol: "YATAS", name: "Yataş Yatak Ve Yorgan", sector: "Perakende"),
        Stock(id: "YKSLN.IS", symbol: "YKSLN", name: "Yükselen Çelik", sector: "Perakende"),

        // MARK: - Sağlık
        Stock(id: "ANGEN.IS", symbol: "ANGEN", name: "Anatolia Tanı Ve Biyoteknoloji", sector: "Sağlık"),
        Stock(id: "AVHOL.IS", symbol: "AVHOL", name: "Avrupa Yatırım Holding", sector: "Sağlık"),
        Stock(id: "DEVA.IS", symbol: "DEVA", name: "Deva Holding", sector: "Sağlık"),
        Stock(id: "ECILC.IS", symbol: "ECILC", name: "Eis Eczacıbaşı İlaç Sınai Ve", sector: "Sağlık"),
        Stock(id: "EGEPO.IS", symbol: "EGEPO", name: "Nasmed Özel Sağlık Hizmetleri", sector: "Sağlık"),
        Stock(id: "GENIL.IS", symbol: "GENIL", name: "Gen İlaç Ve Sağlık Ürünleri", sector: "Sağlık"),
        Stock(id: "KAYSE.IS", symbol: "KAYSE", name: "Kayseri Şeker Fabrikası", sector: "Sağlık"),
        Stock(id: "LKMNH.IS", symbol: "LKMNH", name: "Lokman Hekim Engürüsağ Sağlık", sector: "Sağlık"),
        Stock(id: "MEDTR.IS", symbol: "MEDTR", name: "Meditera Tıbbi Malzeme", sector: "Sağlık"),
        Stock(id: "MPARK.IS", symbol: "MPARK", name: "Mlp Sağlık Hizmetleri", sector: "Sağlık"),
        Stock(id: "ONCSM.IS", symbol: "ONCSM", name: "Oncosem Onkolojik Sistemler", sector: "Sağlık"),
        Stock(id: "RTALB.IS", symbol: "RTALB", name: "Rta Laboratuvarları Biyolojik", sector: "Sağlık"),
        Stock(id: "SEYKM.IS", symbol: "SEYKM", name: "Seyitler Kimya", sector: "Sağlık"),
        Stock(id: "TNZTP.IS", symbol: "TNZTP", name: "Tapdi Oksijen Özel Sağlık Ve Eğitim", sector: "Sağlık"),
        Stock(id: "TRILC.IS", symbol: "TRILC", name: "Turk İlaç Ve Serum", sector: "Sağlık"),

        // MARK: - Sanayi
        Stock(id: "ADEL.IS", symbol: "ADEL", name: "Adel Kalemcilik", sector: "Sanayi"),
        Stock(id: "ALCAR.IS", symbol: "ALCAR", name: "Alarko Carrıer", sector: "Sanayi"),
        Stock(id: "ALVES.IS", symbol: "ALVES", name: "Alves Kablo Sanayi Ve Ticaret A. S.", sector: "Sanayi"),
        Stock(id: "ARCLK.IS", symbol: "ARCLK", name: "Arçelik", sector: "Sanayi"),
        Stock(id: "ASTOR.IS", symbol: "ASTOR", name: "Astor Enerji", sector: "Sanayi"),
        Stock(id: "ASUZU.IS", symbol: "ASUZU", name: "Anadolu Isuzu Otomotiv", sector: "Sanayi"),
        Stock(id: "BAGFS.IS", symbol: "BAGFS", name: "Bagfaş Bandırma Gübre Fabrikaları", sector: "Sanayi"),
        Stock(id: "BALAT.IS", symbol: "BALAT", name: "Balatacılar Balatacılık", sector: "Sanayi"),
        Stock(id: "BANVT.IS", symbol: "BANVT", name: "Banvit Bandırma Vitaminli Yem", sector: "Sanayi"),
        Stock(id: "BERA.IS", symbol: "BERA", name: "Bera Holding", sector: "Sanayi"),
        Stock(id: "BIENY.IS", symbol: "BIENY", name: "Bien Yapı Ürünleri Sanayi Turizm", sector: "Sanayi"),
        Stock(id: "BORSK.IS", symbol: "BORSK", name: "Bor Seker", sector: "Sanayi"),
        Stock(id: "BRISA.IS", symbol: "BRISA", name: "Brisa Brıdgestone Sabancı Lastik", sector: "Sanayi"),
        Stock(id: "BRKO.IS", symbol: "BRKO", name: "Birko Birleşik Koyunlulular", sector: "Sanayi"),
        Stock(id: "BRLSM.IS", symbol: "BRLSM", name: "Birleşim Mühendislik Isıtma Soğutma", sector: "Sanayi"),
        Stock(id: "BVSAN.IS", symbol: "BVSAN", name: "Bülbüloğlu Vinç", sector: "Sanayi"),
        Stock(id: "CEMAS.IS", symbol: "CEMAS", name: "Çemaş Döküm", sector: "Sanayi"),
        Stock(id: "CGCAM.IS", symbol: "CGCAM", name: "Cagdas Cam Sanayi Ve Ticaret AS", sector: "Sanayi"),
        Stock(id: "DGNMO.IS", symbol: "DGNMO", name: "Doğanlar Mobilya Grubu İmalat", sector: "Sanayi"),
        Stock(id: "DITAS.IS", symbol: "DITAS", name: "Ditaş Doğan Yedek Parça İmalat Ve", sector: "Sanayi"),
        Stock(id: "DMSAS.IS", symbol: "DMSAS", name: "Demisaş Döküm Emaye Mamülleri", sector: "Sanayi"),
        Stock(id: "DOFER.IS", symbol: "DOFER", name: "Dofer Yapi Maizemeleri Sanayi", sector: "Sanayi"),
        Stock(id: "DOFRB.IS", symbol: "DOFRB", name: "Dof Robotik Sanayi Anonim Sirketi", sector: "Sanayi"),
        Stock(id: "DOKTA.IS", symbol: "DOKTA", name: "Döktaş Dökümcülük", sector: "Sanayi"),
        Stock(id: "EGEEN.IS", symbol: "EGEEN", name: "Ege Endüstri", sector: "Sanayi"),
        Stock(id: "EGGUB.IS", symbol: "EGGUB", name: "Ege Gübre Sanayii", sector: "Sanayi"),
        Stock(id: "EKOS.IS", symbol: "EKOS", name: "Ekos Teknoloji Ve Elektrik AS", sector: "Sanayi"),
        Stock(id: "EMKEL.IS", symbol: "EMKEL", name: "Emek Elektrik Endüstrisi", sector: "Sanayi"),
        Stock(id: "EPLAS.IS", symbol: "EPLAS", name: "Egeplast Ege Plastik", sector: "Sanayi"),
        Stock(id: "EUPWR.IS", symbol: "EUPWR", name: "Europower Enerji Ve Otomasyon", sector: "Sanayi"),
        Stock(id: "EUREN.IS", symbol: "EUREN", name: "Europen Endüstri İnşaat", sector: "Sanayi"),
        Stock(id: "FROTO.IS", symbol: "FROTO", name: "Ford Otomotiv", sector: "Sanayi"),
        Stock(id: "FZLGY.IS", symbol: "FZLGY", name: "Fuzul Gayrımenkul Yatırım Ortaklıgı", sector: "Sanayi"),
        Stock(id: "GENTS.IS", symbol: "GENTS", name: "Gentaş Dekoratif Yüzeyler", sector: "Sanayi"),
        Stock(id: "GEREL.IS", symbol: "GEREL", name: "Gersan Elektrik", sector: "Sanayi"),
        Stock(id: "GIPTA.IS", symbol: "GIPTA", name: "Gipta Ofis Kirtasiye Ve Promosyon", sector: "Sanayi"),
        Stock(id: "GOODY.IS", symbol: "GOODY", name: "Goodyear Lastikleri", sector: "Sanayi"),
        Stock(id: "GUBRF.IS", symbol: "GUBRF", name: "Gübre Fabrikaları", sector: "Sanayi"),
        Stock(id: "HATSN.IS", symbol: "HATSN", name: "Hat-san Gemi Insaa Bakim Onarim", sector: "Sanayi"),
        Stock(id: "HKTM.IS", symbol: "HKTM", name: "Hidropar Hareket Kontrol", sector: "Sanayi"),
        Stock(id: "IEYHO.IS", symbol: "IEYHO", name: "Işıklar Enerji Ve Yapı Holding", sector: "Sanayi"),
        Stock(id: "IHEVA.IS", symbol: "IHEVA", name: "İhlas Ev Aletleri İmalat", sector: "Sanayi"),
        Stock(id: "IMASM.IS", symbol: "IMASM", name: "İmaş Makina", sector: "Sanayi"),
        Stock(id: "INTEK.IS", symbol: "INTEK", name: "Innosa Teknoloji Anonim Sirketi", sector: "Sanayi"),
        Stock(id: "INTEM.IS", symbol: "INTEM", name: "İntema İnşaat Ve Tesisat", sector: "Sanayi"),
        Stock(id: "ISBIR.IS", symbol: "ISBIR", name: "İşbir Holding", sector: "Sanayi"),
        Stock(id: "ISKPL.IS", symbol: "ISKPL", name: "Işık Plastik Sanayi Ve Dış Ticaret", sector: "Sanayi"),
        Stock(id: "ISSEN.IS", symbol: "ISSEN", name: "İşbir Sentetik Dokuma", sector: "Sanayi"),
        Stock(id: "IZFAS.IS", symbol: "IZFAS", name: "İzmir Fırça", sector: "Sanayi"),
        Stock(id: "JANTS.IS", symbol: "JANTS", name: "Jantsa Jant", sector: "Sanayi"),
        Stock(id: "KATMR.IS", symbol: "KATMR", name: "Katmerciler Araç Üstü Ekipman", sector: "Sanayi"),
        Stock(id: "KBORU.IS", symbol: "KBORU", name: "Kuzey Boru", sector: "Sanayi"),
        Stock(id: "KLMSN.IS", symbol: "KLMSN", name: "Klimasan Klima", sector: "Sanayi"),
        Stock(id: "KLSYN.IS", symbol: "KLSYN", name: "Koleksiyon Mobilya", sector: "Sanayi"),
        Stock(id: "KLYPV.IS", symbol: "KLYPV", name: "Kalyon Gunes Teknolojileri Uretim", sector: "Sanayi"),
        Stock(id: "KMPUR.IS", symbol: "KMPUR", name: "Kimteks Poliüretan", sector: "Sanayi"),
        Stock(id: "KRONT.IS", symbol: "KRONT", name: "Kron Telekomünikasyon Hizmetleri", sector: "Sanayi"),
        Stock(id: "KUTPO.IS", symbol: "KUTPO", name: "Kütahya Porselen", sector: "Sanayi"),
        Stock(id: "KUVVA.IS", symbol: "KUVVA", name: "Kuvva Gıda Ticaret Ve Sanayi", sector: "Sanayi"),
        Stock(id: "LMKDC.IS", symbol: "LMKDC", name: "Limak Dogu Anadolu Cimento Sanayi", sector: "Sanayi"),
        Stock(id: "MAKTK.IS", symbol: "MAKTK", name: "Makina Takım Endüstrisi", sector: "Sanayi"),
        Stock(id: "MANAS.IS", symbol: "MANAS", name: "Manas Enerji Yönetimi", sector: "Sanayi"),
        Stock(id: "MEKAG.IS", symbol: "MEKAG", name: "Meka Global Makine Imalat Sanayi", sector: "Sanayi"),
        Stock(id: "MRSHL.IS", symbol: "MRSHL", name: "Marshall Boya Ve Vernik Sanayii", sector: "Sanayi"),
        Stock(id: "MZHLD.IS", symbol: "MZHLD", name: "Mazhar Zorlu Holding", sector: "Sanayi"),
        Stock(id: "ORMA.IS", symbol: "ORMA", name: "Orma Orman Mahsulleri İntegre", sector: "Sanayi"),
        Stock(id: "OTKAR.IS", symbol: "OTKAR", name: "Otokar Otomotiv Ve Savunma", sector: "Sanayi"),
        Stock(id: "OTTO.IS", symbol: "OTTO", name: "Otto Holding", sector: "Sanayi"),
        Stock(id: "OZATD.IS", symbol: "OZATD", name: "Ozata Denızcılık Sanayı Ve Tıcaret", sector: "Sanayi"),
        Stock(id: "OZSUB.IS", symbol: "OZSUB", name: "Özsu Balık Üretim", sector: "Sanayi"),
        Stock(id: "OZYSR.IS", symbol: "OZYSR", name: "Ozyasar Tel Ve Galvanizleme Sanayi", sector: "Sanayi"),
        Stock(id: "PARSN.IS", symbol: "PARSN", name: "Parsan Makina Parçaları Sanayii", sector: "Sanayi"),
        Stock(id: "PNLSN.IS", symbol: "PNLSN", name: "Panelsan Çatı Cephe Sistemleri", sector: "Sanayi"),
        Stock(id: "POLHO.IS", symbol: "POLHO", name: "Polisan Holding", sector: "Sanayi"),
        Stock(id: "PRKAB.IS", symbol: "PRKAB", name: "Türk Prysmian Kablo Ve Sistemleri", sector: "Sanayi"),
        Stock(id: "QUAGR.IS", symbol: "QUAGR", name: "Qua Granıte Hayal Yapı Ve Ürünleri", sector: "Sanayi"),
        Stock(id: "RNPOL.IS", symbol: "RNPOL", name: "Rainbow Polikarbonat", sector: "Sanayi"),
        Stock(id: "SAFKR.IS", symbol: "SAFKR", name: "Safkar Ege Soğutmacılık Klima Soğuk", sector: "Sanayi"),
        Stock(id: "SANEL.IS", symbol: "SANEL", name: "San-el Mühendislik Elektrik Taahhüt", sector: "Sanayi"),
        Stock(id: "SANKO.IS", symbol: "SANKO", name: "Sanko Pazarlama İthalat İhracat", sector: "Sanayi"),
        Stock(id: "SARKY.IS", symbol: "SARKY", name: "Sarkuysan Elektrolitik Bakır", sector: "Sanayi"),
        Stock(id: "SASA.IS", symbol: "SASA", name: "Sasa Polyester", sector: "Sanayi"),
        Stock(id: "SAYAS.IS", symbol: "SAYAS", name: "Say Yenilenebilir Enerji", sector: "Sanayi"),
        Stock(id: "SILVR.IS", symbol: "SILVR", name: "Silverline Endüstri", sector: "Sanayi"),
        Stock(id: "SISE.IS", symbol: "SISE", name: "Türkiye Şişe Ve Cam Fabrikaları", sector: "Sanayi"),
        Stock(id: "SNICA.IS", symbol: "SNICA", name: "Sanica Isı", sector: "Sanayi"),
        Stock(id: "SNPAM.IS", symbol: "SNPAM", name: "Sönmez Pamuklu Sanayii", sector: "Sanayi"),
        Stock(id: "SODSN.IS", symbol: "SODSN", name: "Sodaş Sodyum Sanayii", sector: "Sanayi"),
        Stock(id: "SUMAS.IS", symbol: "SUMAS", name: "Sumaş Suni Tahta Ve Mobilya", sector: "Sanayi"),
        Stock(id: "TCELL.IS", symbol: "TCELL", name: "Turkcell İletişim Hizmetleri", sector: "Sanayi"),
        Stock(id: "TMSN.IS", symbol: "TMSN", name: "Tümosan Motor Ve Traktör", sector: "Sanayi"),
        Stock(id: "TOASO.IS", symbol: "TOASO", name: "Tofaş Türk Otomobil Fabrikası", sector: "Sanayi"),
        Stock(id: "TRALT.IS", symbol: "TRALT", name: "Turk Altin Isletmeleri", sector: "Sanayi"),
        Stock(id: "TTKOM.IS", symbol: "TTKOM", name: "Türk Telekomünikasyon", sector: "Sanayi"),
        Stock(id: "TTRAK.IS", symbol: "TTRAK", name: "Türk Traktör Ve Ziraat Makineleri", sector: "Sanayi"),
        Stock(id: "ULUSE.IS", symbol: "ULUSE", name: "Ulusoy Elektrik İmalat Taahhüt", sector: "Sanayi"),
        Stock(id: "VESBE.IS", symbol: "VESBE", name: "Vestel Beyaz Eşya", sector: "Sanayi"),
        Stock(id: "VESTL.IS", symbol: "VESTL", name: "Vestel Elektronik", sector: "Sanayi"),
        Stock(id: "YBTAS.IS", symbol: "YBTAS", name: "Yibitaş Yozgat İşçi Birliği İnşaat", sector: "Sanayi"),
        Stock(id: "YIGIT.IS", symbol: "YIGIT", name: "Yigit Aku Malzemeleri Nakliyat", sector: "Sanayi"),
        Stock(id: "YONGA.IS", symbol: "YONGA", name: "Yonga Mobilya", sector: "Sanayi"),

        // MARK: - Savunma
        Stock(id: "ALTNY.IS", symbol: "ALTNY", name: "Altinay Savunma Teknolojileri", sector: "Savunma"),
        Stock(id: "PAPIL.IS", symbol: "PAPIL", name: "Papilon Savunma Teknoloji", sector: "Savunma"),
        Stock(id: "SDTTR.IS", symbol: "SDTTR", name: "Sdt Uzay Ve Savunma Teknolojileri", sector: "Savunma"),

        // MARK: - Seramik
        Stock(id: "EGSER.IS", symbol: "EGSER", name: "Ege Seramik", sector: "Seramik"),
        Stock(id: "KLSER.IS", symbol: "KLSER", name: "Kaleseramik Canakkale Kalebodur", sector: "Seramik"),
        Stock(id: "SERNT.IS", symbol: "SERNT", name: "Seranit Granit Seramik Sanayi", sector: "Seramik"),
        Stock(id: "USAK.IS", symbol: "USAK", name: "Uşak Seramik", sector: "Seramik"),

        // MARK: - Sigorta
        Stock(id: "AKGRT.IS", symbol: "AKGRT", name: "Aksigorta", sector: "Sigorta"),
        Stock(id: "ANSGR.IS", symbol: "ANSGR", name: "Anadolu Anonim Türk Sigorta Şirketi", sector: "Sigorta"),
        Stock(id: "RAYSG.IS", symbol: "RAYSG", name: "Ray Sigorta", sector: "Sigorta"),
        Stock(id: "TURSG.IS", symbol: "TURSG", name: "Türkiye Sigorta", sector: "Sigorta"),

        // MARK: - Teknoloji
        Stock(id: "AGROT.IS", symbol: "AGROT", name: "Agrotech Yuksek Teknoloji Ve", sector: "Teknoloji"),
        Stock(id: "ALCTL.IS", symbol: "ALCTL", name: "Alcatel Lucent Teletaş", sector: "Teknoloji"),
        Stock(id: "ARDYZ.IS", symbol: "ARDYZ", name: "Ard Grup Bilişim Teknolojileri", sector: "Teknoloji"),
        Stock(id: "ASELS.IS", symbol: "ASELS", name: "Aselsan Elektronik", sector: "Teknoloji"),
        Stock(id: "ATATP.IS", symbol: "ATATP", name: "Atp Yazılım Ve Teknoloji", sector: "Teknoloji"),
        Stock(id: "BINHO.IS", symbol: "BINHO", name: "1000 Yatirimlar Holding AS", sector: "Teknoloji"),
        Stock(id: "CWENE.IS", symbol: "CWENE", name: "Cw Enerji Mühendislik", sector: "Teknoloji"),
        Stock(id: "EMPAE.IS", symbol: "EMPAE", name: "Empa Elektronik Sanayi", sector: "Teknoloji"),
        Stock(id: "ESCOM.IS", symbol: "ESCOM", name: "Escort Teknoloji Yatırım", sector: "Teknoloji"),
        Stock(id: "FONET.IS", symbol: "FONET", name: "Fonet Bilgi Teknolojileri", sector: "Teknoloji"),
        Stock(id: "FORTE.IS", symbol: "FORTE", name: "Forte Bılgı Iletısım Teknolojılerı", sector: "Teknoloji"),
        Stock(id: "GESAN.IS", symbol: "GESAN", name: "Girişim Elektrik Sanayi Taahhüt", sector: "Teknoloji"),
        Stock(id: "HTTBT.IS", symbol: "HTTBT", name: "Hitit Bilgisayar Hizmetleri", sector: "Teknoloji"),
        Stock(id: "KAREL.IS", symbol: "KAREL", name: "Karel Elektronik", sector: "Teknoloji"),
        Stock(id: "KFEIN.IS", symbol: "KFEIN", name: "Kafein Yazılım Hizmetleri", sector: "Teknoloji"),
        Stock(id: "LINK.IS", symbol: "LINK", name: "Link Bilgisayar Sistemleri Yazılımı", sector: "Teknoloji"),
        Stock(id: "LOGO.IS", symbol: "LOGO", name: "Logo Yazılım", sector: "Teknoloji"),
        Stock(id: "MAKIM.IS", symbol: "MAKIM", name: "Makim Makina Teknolojileri", sector: "Teknoloji"),
        Stock(id: "MIATK.IS", symbol: "MIATK", name: "Mia Teknoloji", sector: "Teknoloji"),
        Stock(id: "MTRKS.IS", symbol: "MTRKS", name: "Matriks Finansal Teknolojiler", sector: "Teknoloji"),
        Stock(id: "NETAS.IS", symbol: "NETAS", name: "Netaş Telekomünikasyon", sector: "Teknoloji"),
        Stock(id: "NETCD.IS", symbol: "NETCD", name: "Netcad Yazilim", sector: "Teknoloji"),
        Stock(id: "OBASE.IS", symbol: "OBASE", name: "Obase Bilgisayar Ve Danışmanlık", sector: "Teknoloji"),
        Stock(id: "ODINE.IS", symbol: "ODINE", name: "Odine Solutions Teknoloji Ticaret", sector: "Teknoloji"),
        Stock(id: "ONRYT.IS", symbol: "ONRYT", name: "Onur Yuksek Teknoloji AS", sector: "Teknoloji"),
        Stock(id: "PATEK.IS", symbol: "PATEK", name: "Pasifik Teknoloji AS", sector: "Teknoloji"),
        Stock(id: "REEDR.IS", symbol: "REEDR", name: "Reeder Teknoloji Sanayi", sector: "Teknoloji"),
        Stock(id: "SMART.IS", symbol: "SMART", name: "Smartiks Yazılım", sector: "Teknoloji"),
        Stock(id: "SMRTG.IS", symbol: "SMRTG", name: "Smart Güneş Enerjisi Teknolojileri", sector: "Teknoloji"),
        Stock(id: "VBTYZ.IS", symbol: "VBTYZ", name: "Vbt Yazılım", sector: "Teknoloji"),

        // MARK: - Tekstil
        Stock(id: "ARSAN.IS", symbol: "ARSAN", name: "Arsan Tekstil", sector: "Tekstil"),
        Stock(id: "ATEKS.IS", symbol: "ATEKS", name: "Akın Tekstil", sector: "Tekstil"),
        Stock(id: "BRMEN.IS", symbol: "BRMEN", name: "Birlik Mensucat Ticaret Ve Sanayi", sector: "Tekstil"),
        Stock(id: "DAGI.IS", symbol: "DAGI", name: "Dagi Giyim", sector: "Tekstil"),
        Stock(id: "DERIM.IS", symbol: "DERIM", name: "Derimod Konfeksiyon Ayakkabı Deri", sector: "Tekstil"),
        Stock(id: "DIRIT.IS", symbol: "DIRIT", name: "Diriteks Diriliş Tekstil", sector: "Tekstil"),
        Stock(id: "HATEK.IS", symbol: "HATEK", name: "Hateks Hatay Tekstil İşletmeleri", sector: "Tekstil"),
        Stock(id: "KORDS.IS", symbol: "KORDS", name: "Kordsa Teknik Tekstil", sector: "Tekstil"),
        Stock(id: "KOTON.IS", symbol: "KOTON", name: "Koton Mağazacılık Tekstil", sector: "Tekstil"),
        Stock(id: "KRTEK.IS", symbol: "KRTEK", name: "Karsu Tekstil Sanayii", sector: "Tekstil"),
        Stock(id: "MAVI.IS", symbol: "MAVI", name: "Mavi Giyim", sector: "Tekstil"),
        Stock(id: "MNDRS.IS", symbol: "MNDRS", name: "Menderes Tekstil", sector: "Tekstil"),
        Stock(id: "RODRG.IS", symbol: "RODRG", name: "Rodrigo Tekstil", sector: "Tekstil"),
        Stock(id: "RUBNS.IS", symbol: "RUBNS", name: "Rubenis Tekstil", sector: "Tekstil"),
        Stock(id: "SKTAS.IS", symbol: "SKTAS", name: "Söktaş Tekstil", sector: "Tekstil"),
        Stock(id: "SONME.IS", symbol: "SONME", name: "Sönmez Filament Sentetik İplik Ve", sector: "Tekstil"),
        Stock(id: "SUNTK.IS", symbol: "SUNTK", name: "Sun Tekstil", sector: "Tekstil"),
        Stock(id: "VAKKO.IS", symbol: "VAKKO", name: "Vakko Tekstil Ve Hazır Giyim Sanayi", sector: "Tekstil"),

        // MARK: - Turizm
        Stock(id: "ATATR.IS", symbol: "ATATR", name: "Ata Turizm Isletmecilik Tasimacilik", sector: "Turizm"),
        Stock(id: "AYCES.IS", symbol: "AYCES", name: "Altın Yunus Çeşme Turistik Tesisler", sector: "Turizm"),
        Stock(id: "BIGCH.IS", symbol: "BIGCH", name: "Büyük Şefler Gıda Turizm Tekstil", sector: "Turizm"),
        Stock(id: "BIGTK.IS", symbol: "BIGTK", name: "Big Medya Teknoloji", sector: "Turizm"),
        Stock(id: "BJKAS.IS", symbol: "BJKAS", name: "Beşiktaş Futbol Yatırımları", sector: "Turizm"),
        Stock(id: "BLUME.IS", symbol: "BLUME", name: "Blume Metal Kimya Anonim Sirketi", sector: "Turizm"),
        Stock(id: "BYDNR.IS", symbol: "BYDNR", name: "Baydoner Restoranlari", sector: "Turizm"),
        Stock(id: "CEOEM.IS", symbol: "CEOEM", name: "Ceo Event Medya", sector: "Turizm"),
        Stock(id: "DOCO.IS", symbol: "DOCO", name: "Do & Co Aktıengesellschaft", sector: "Turizm"),
        Stock(id: "ETILR.IS", symbol: "ETILR", name: "Etiler Gıda Ve Ticari Yatırımlar", sector: "Turizm"),
        Stock(id: "FENER.IS", symbol: "FENER", name: "Fenerbahçe Futbol", sector: "Turizm"),
        Stock(id: "FLAP.IS", symbol: "FLAP", name: "Flap Kongre Toplantı Hizmetleri", sector: "Turizm"),
        Stock(id: "GRSEL.IS", symbol: "GRSEL", name: "Gür-sel Turizm Taşımacılık Ve", sector: "Turizm"),
        Stock(id: "GSRAY.IS", symbol: "GSRAY", name: "Galatasaray Sportif Sınai Ve Ticari", sector: "Turizm"),
        Stock(id: "GZNMI.IS", symbol: "GZNMI", name: "Gezinomi Seyahat Turizm", sector: "Turizm"),
        Stock(id: "HURGZ.IS", symbol: "HURGZ", name: "Hürriyet Gazetecilik Ve Matbaacılık", sector: "Turizm"),
        Stock(id: "IHGZT.IS", symbol: "IHGZT", name: "İhlas Gazetecilik", sector: "Turizm"),
        Stock(id: "IHYAY.IS", symbol: "IHYAY", name: "İhlas Yayın Holding", sector: "Turizm"),
        Stock(id: "KERVN.IS", symbol: "KERVN", name: "Kervansaray Yatırım Holding", sector: "Turizm"),
        Stock(id: "KSTUR.IS", symbol: "KSTUR", name: "Kuştur Kuşadası Turizm Endüstri", sector: "Turizm"),
        Stock(id: "MAALT.IS", symbol: "MAALT", name: "Marmaris Altınyunus Turistik", sector: "Turizm"),
        Stock(id: "MARTI.IS", symbol: "MARTI", name: "Martı Otel İşletmeleri", sector: "Turizm"),
        Stock(id: "MERIT.IS", symbol: "MERIT", name: "Merit Turizm Yatırım Ve İşletme", sector: "Turizm"),
        Stock(id: "NTHOL.IS", symbol: "NTHOL", name: "Net Holding", sector: "Turizm"),
        Stock(id: "PKENT.IS", symbol: "PKENT", name: "Petrokent Turizm", sector: "Turizm"),
        Stock(id: "TABGD.IS", symbol: "TABGD", name: "Tab Gida Sanayi", sector: "Turizm"),
        Stock(id: "TEKTU.IS", symbol: "TEKTU", name: "Tek-art İnşaat Ticaret Turizm", sector: "Turizm"),
        Stock(id: "TSPOR.IS", symbol: "TSPOR", name: "Trabzonspor Sportif Yatırım Ve", sector: "Turizm"),
        Stock(id: "ULAS.IS", symbol: "ULAS", name: "Ulaşlar Turizm Yatırımları Ve", sector: "Turizm"),
        Stock(id: "ZEDUR.IS", symbol: "ZEDUR", name: "Zedur Enerji Elektrik Üretim", sector: "Turizm"),
    ]

    // Geriye dönük uyumluluk
    static var bist100: [Stock] { all }
}
