import Foundation

enum BISTStockList {

    static let all: [Stock] = [

        // MARK: - Bankacılık
        Stock(id: "AKBNK.IS", symbol: "AKBNK", name: "Akbank",               sector: "Bankacılık"),
        Stock(id: "GARAN.IS", symbol: "GARAN", name: "Garanti BBVA",         sector: "Bankacılık"),
        Stock(id: "HALKB.IS", symbol: "HALKB", name: "Halkbank",             sector: "Bankacılık"),
        Stock(id: "ISCTR.IS", symbol: "ISCTR", name: "İş Bankası C",         sector: "Bankacılık"),
        Stock(id: "VAKBN.IS", symbol: "VAKBN", name: "Vakıfbank",            sector: "Bankacılık"),
        Stock(id: "YKBNK.IS", symbol: "YKBNK", name: "Yapı Kredi",          sector: "Bankacılık"),
        Stock(id: "QNBFB.IS", symbol: "QNBFB", name: "QNB Finansbank",      sector: "Bankacılık"),
        Stock(id: "ALBRK.IS", symbol: "ALBRK", name: "Albaraka Türk",        sector: "Bankacılık"),
        Stock(id: "TSKB.IS",  symbol: "TSKB",  name: "TSKB",                sector: "Bankacılık"),
        Stock(id: "SKBNK.IS", symbol: "SKBNK", name: "Şekerbank",           sector: "Bankacılık"),
        Stock(id: "ICBCT.IS", symbol: "ICBCT", name: "ICBC Turkey",          sector: "Bankacılık"),
        Stock(id: "BURCE.IS", symbol: "BURCE", name: "Burgan Bank",          sector: "Bankacılık"),
        Stock(id: "ISBTR.IS", symbol: "ISBTR", name: "İş Bankası B",         sector: "Bankacılık"),
        Stock(id: "KUOTK.IS", symbol: "KUOTK", name: "Kuveyt Türk",         sector: "Bankacılık"),

        // MARK: - Holding
        Stock(id: "KCHOL.IS", symbol: "KCHOL", name: "Koç Holding",          sector: "Holding"),
        Stock(id: "SAHOL.IS", symbol: "SAHOL", name: "Sabancı Holding",      sector: "Holding"),
        Stock(id: "DOHOL.IS", symbol: "DOHOL", name: "Doğan Holding",        sector: "Holding"),
        Stock(id: "GLYHO.IS", symbol: "GLYHO", name: "Global Yatırım H.",   sector: "Holding"),
        Stock(id: "YAZIC.IS", symbol: "YAZIC", name: "Yazıcılar Holding",    sector: "Holding"),
        Stock(id: "TKFEN.IS", symbol: "TKFEN", name: "Tekfen Holding",       sector: "Holding"),
        Stock(id: "AGHOL.IS", symbol: "AGHOL", name: "AG Anadolu Grubu",    sector: "Holding"),
        Stock(id: "ALARK.IS", symbol: "ALARK", name: "Alarko Holding",       sector: "Holding"),
        Stock(id: "BERA.IS",  symbol: "BERA",  name: "Bera Holding",         sector: "Holding"),
        Stock(id: "GOZDE.IS", symbol: "GOZDE", name: "Gözde Girişim",       sector: "Holding"),
        Stock(id: "NTHOL.IS", symbol: "NTHOL", name: "Net Holding",          sector: "Holding"),
        Stock(id: "POLHO.IS", symbol: "POLHO", name: "Polisan Holding",      sector: "Holding"),
        Stock(id: "ITTFK.IS", symbol: "ITTFK", name: "İttifak Holding",     sector: "Holding"),
        Stock(id: "IHLAS.IS", symbol: "IHLAS", name: "İhlas Holding",        sector: "Holding"),
        Stock(id: "KTLEV.IS", symbol: "KTLEV", name: "KT Levent",            sector: "Holding"),

        // MARK: - Havacılık & Ulaşım
        Stock(id: "THYAO.IS", symbol: "THYAO", name: "Türk Hava Yolları",   sector: "Havacılık"),
        Stock(id: "PGSUS.IS", symbol: "PGSUS", name: "Pegasus",              sector: "Havacılık"),
        Stock(id: "TAVHL.IS", symbol: "TAVHL", name: "TAV Havalimanları",   sector: "Havacılık"),
        Stock(id: "HAVAS.IS", symbol: "HAVAS", name: "Havaş",               sector: "Havacılık"),
        Stock(id: "CLEBI.IS", symbol: "CLEBI", name: "Çelebi Havacılık",    sector: "Havacılık"),
        Stock(id: "UCAK.IS",  symbol: "UCAK",  name: "Uçak Servisi",        sector: "Havacılık"),

        // MARK: - Savunma & Teknoloji
        Stock(id: "ASELS.IS", symbol: "ASELS", name: "Aselsan",              sector: "Savunma"),
        Stock(id: "KATMR.IS", symbol: "KATMR", name: "Katmerciler",          sector: "Savunma"),
        Stock(id: "LOGO.IS",  symbol: "LOGO",  name: "Logo Yazılım",         sector: "Teknoloji"),
        Stock(id: "ALCTL.IS", symbol: "ALCTL", name: "Alcatel Lucent",       sector: "Teknoloji"),
        Stock(id: "NETAS.IS", symbol: "NETAS", name: "Netaş",               sector: "Teknoloji"),
        Stock(id: "INDES.IS", symbol: "INDES", name: "İndeks Bilgisayar",   sector: "Teknoloji"),
        Stock(id: "KAREL.IS", symbol: "KAREL", name: "Karel Elektronik",     sector: "Teknoloji"),
        Stock(id: "LINK.IS",  symbol: "LINK",  name: "Link Bilgisayar",      sector: "Teknoloji"),
        Stock(id: "VBTYZ.IS", symbol: "VBTYZ", name: "VBT Yazılım",         sector: "Teknoloji"),
        Stock(id: "ESCOM.IS", symbol: "ESCOM", name: "Escort Teknoloji",     sector: "Teknoloji"),
        Stock(id: "DGATE.IS", symbol: "DGATE", name: "Datagate",             sector: "Teknoloji"),
        Stock(id: "PRKME.IS", symbol: "PRKME", name: "Park Elektrik",        sector: "Teknoloji"),
        Stock(id: "KRONT.IS", symbol: "KRONT", name: "Kronos",               sector: "Teknoloji"),
        Stock(id: "MIATK.IS", symbol: "MIATK", name: "Mia Teknoloji",        sector: "Teknoloji"),
        Stock(id: "BORSK.IS", symbol: "BORSK", name: "Borska",               sector: "Teknoloji"),
        Stock(id: "OBASE.IS", symbol: "OBASE", name: "Obase Bilgisayar",     sector: "Teknoloji"),

        // MARK: - Enerji
        Stock(id: "TUPRS.IS", symbol: "TUPRS", name: "Tüpraş",              sector: "Enerji"),
        Stock(id: "AKSEN.IS", symbol: "AKSEN", name: "Aksa Enerji",          sector: "Enerji"),
        Stock(id: "ZOREN.IS", symbol: "ZOREN", name: "Zorlu Enerji",         sector: "Enerji"),
        Stock(id: "ODAS.IS",  symbol: "ODAS",  name: "Odaş Elektrik",       sector: "Enerji"),
        Stock(id: "AYEN.IS",  symbol: "AYEN",  name: "Ayen Enerji",          sector: "Enerji"),
        Stock(id: "ONRYT.IS", symbol: "ONRYT", name: "Onur Enerji",          sector: "Enerji"),
        Stock(id: "ORGE.IS",  symbol: "ORGE",  name: "Orge Enerji",          sector: "Enerji"),
        Stock(id: "AKENR.IS", symbol: "AKENR", name: "Ak Enerji",            sector: "Enerji"),
        Stock(id: "BIOEN.IS", symbol: "BIOEN", name: "Bio Enerji",           sector: "Enerji"),
        Stock(id: "GWIND.IS", symbol: "GWIND", name: "Galata Wind",          sector: "Enerji"),
        Stock(id: "EUPWR.IS", symbol: "EUPWR", name: "European Power",       sector: "Enerji"),
        Stock(id: "NATEN.IS", symbol: "NATEN", name: "Naturel Enerji",       sector: "Enerji"),
        Stock(id: "TUREX.IS", symbol: "TUREX", name: "Türkerler Enerji",    sector: "Enerji"),
        Stock(id: "KCAER.IS", symbol: "KCAER", name: "KC Enerji",            sector: "Enerji"),
        Stock(id: "SMRTG.IS", symbol: "SMRTG", name: "Smart Güneş",         sector: "Enerji"),
        Stock(id: "AYGAZ.IS", symbol: "AYGAZ", name: "Aygaz",               sector: "Enerji"),
        Stock(id: "PETKM.IS", symbol: "PETKM", name: "Petkim",               sector: "Enerji"),
        Stock(id: "IEDAS.IS", symbol: "IEDAS", name: "İED AŞ",              sector: "Enerji"),
        Stock(id: "ALFAS.IS", symbol: "ALFAS", name: "Alfa Solar",           sector: "Enerji"),
        Stock(id: "SANKO.IS", symbol: "SANKO", name: "Sanko Güneş",         sector: "Enerji"),

        // MARK: - Petrokimya & Kimya
        Stock(id: "AKSA.IS",  symbol: "AKSA",  name: "Aksa Akrilik",         sector: "Kimya"),
        Stock(id: "SASA.IS",  symbol: "SASA",  name: "Sasa Polyester",       sector: "Kimya"),
        Stock(id: "GUBRF.IS", symbol: "GUBRF", name: "Gübre Fabrikaları",    sector: "Kimya"),
        Stock(id: "ALKIM.IS", symbol: "ALKIM", name: "Alkim Kimya",          sector: "Kimya"),
        Stock(id: "HEKTS.IS", symbol: "HEKTS", name: "Hektaş",              sector: "Kimya"),
        Stock(id: "EGGUB.IS", symbol: "EGGUB", name: "Ege Gübre",           sector: "Kimya"),
        Stock(id: "EPLAS.IS", symbol: "EPLAS", name: "Ege Plastik",          sector: "Kimya"),
        Stock(id: "BAGFS.IS", symbol: "BAGFS", name: "Bağfaş",              sector: "Kimya"),
        Stock(id: "CANTE.IS", symbol: "CANTE", name: "Can Tarım",            sector: "Kimya"),
        Stock(id: "EGEEN.IS", symbol: "EGEEN", name: "Ege Endüstri",        sector: "Kimya"),
        Stock(id: "KLMSN.IS", symbol: "KLMSN", name: "Klimasan",             sector: "Kimya"),

        // MARK: - İlaç & Sağlık
        Stock(id: "ECILC.IS", symbol: "ECILC", name: "Eczacıbaşı İlaç",    sector: "İlaç"),
        Stock(id: "ECZYT.IS", symbol: "ECZYT", name: "Eczacıbaşı Yatırım", sector: "İlaç"),
        Stock(id: "SELEC.IS", symbol: "SELEC", name: "Selçuk Ecza",         sector: "İlaç"),
        Stock(id: "DEVA.IS",  symbol: "DEVA",  name: "Deva Holding",         sector: "İlaç"),
        Stock(id: "RTALB.IS", symbol: "RTALB", name: "Rotor Alüminyum",     sector: "İlaç"),
        Stock(id: "MPARK.IS", symbol: "MPARK", name: "MLP Care",             sector: "Sağlık"),

        // MARK: - Otomotiv & Lastik
        Stock(id: "FROTO.IS", symbol: "FROTO", name: "Ford Otosan",          sector: "Otomotiv"),
        Stock(id: "TOASO.IS", symbol: "TOASO", name: "Tofaş",               sector: "Otomotiv"),
        Stock(id: "TTRAK.IS", symbol: "TTRAK", name: "Türk Traktör",        sector: "Otomotiv"),
        Stock(id: "OTKAR.IS", symbol: "OTKAR", name: "Otokar",               sector: "Otomotiv"),
        Stock(id: "DOAS.IS",  symbol: "DOAS",  name: "Doğuş Otomotiv",      sector: "Otomotiv"),
        Stock(id: "ASUZU.IS", symbol: "ASUZU", name: "Anadolu Isuzu",       sector: "Otomotiv"),
        Stock(id: "KARSN.IS", symbol: "KARSN", name: "Karsan",               sector: "Otomotiv"),
        Stock(id: "BRYAT.IS", symbol: "BRYAT", name: "Borusan Otomotiv",    sector: "Otomotiv"),
        Stock(id: "MUTLU.IS", symbol: "MUTLU", name: "Mutlu Akü",           sector: "Otomotiv"),
        Stock(id: "JANTS.IS", symbol: "JANTS", name: "Jantsa Jant",         sector: "Otomotiv"),
        Stock(id: "BRISA.IS", symbol: "BRISA", name: "Brisa",               sector: "Lastik"),
        Stock(id: "GOODY.IS", symbol: "GOODY", name: "Goodyear",             sector: "Lastik"),

        // MARK: - Beyaz Eşya & Elektronik
        Stock(id: "ARCLK.IS", symbol: "ARCLK", name: "Arçelik",             sector: "Beyaz Eşya"),
        Stock(id: "VESTL.IS", symbol: "VESTL", name: "Vestel",               sector: "Elektronik"),
        Stock(id: "VESBE.IS", symbol: "VESBE", name: "Vestel Beyaz Eşya",  sector: "Beyaz Eşya"),
        Stock(id: "IHEVA.IS", symbol: "IHEVA", name: "İhlas Ev Aletleri",   sector: "Beyaz Eşya"),

        // MARK: - Demir-Çelik & Metal
        Stock(id: "EREGL.IS", symbol: "EREGL", name: "Ereğli Demir Çelik", sector: "Demir-Çelik"),
        Stock(id: "KRDMD.IS", symbol: "KRDMD", name: "Kardemir D",          sector: "Demir-Çelik"),
        Stock(id: "KRDMB.IS", symbol: "KRDMB", name: "Kardemir B",          sector: "Demir-Çelik"),
        Stock(id: "IZMDC.IS", symbol: "IZMDC", name: "İzmir Demir Çelik",  sector: "Demir-Çelik"),
        Stock(id: "BRSAN.IS", symbol: "BRSAN", name: "Borusan Mannesmann",  sector: "Metal"),
        Stock(id: "CELHA.IS", symbol: "CELHA", name: "Çelik Halat",        sector: "Metal"),
        Stock(id: "SARKY.IS", symbol: "SARKY", name: "Sarkuysan",           sector: "Metal"),
        Stock(id: "EMKEL.IS", symbol: "EMKEL", name: "Emek Elektrik",       sector: "Metal"),
        Stock(id: "PARSN.IS", symbol: "PARSN", name: "Parsan",              sector: "Metal"),
        Stock(id: "DITAS.IS", symbol: "DITAS", name: "Ditaş",              sector: "Metal"),
        Stock(id: "CEMAS.IS", symbol: "CEMAS", name: "Çemaş Döküm",        sector: "Metal"),
        Stock(id: "PRKAB.IS", symbol: "PRKAB", name: "Türk Prysmian Kablo", sector: "Metal"),

        // MARK: - Cam & Seramik
        Stock(id: "SISE.IS",  symbol: "SISE",  name: "Şişe Cam",           sector: "Cam"),
        Stock(id: "TRKCM.IS", symbol: "TRKCM", name: "Trakya Cam",          sector: "Cam"),
        Stock(id: "ANACM.IS", symbol: "ANACM", name: "Anadolu Cam",         sector: "Cam"),

        // MARK: - Çimento & İnşaat Malz.
        Stock(id: "CIMSA.IS", symbol: "CIMSA", name: "Çimsa",              sector: "Çimento"),
        Stock(id: "AKCNS.IS", symbol: "AKCNS", name: "Akçansa",            sector: "Çimento"),
        Stock(id: "ADANA.IS", symbol: "ADANA", name: "Adana Çimento A",    sector: "Çimento"),
        Stock(id: "ADNAC.IS", symbol: "ADNAC", name: "Adana Çimento C",    sector: "Çimento"),
        Stock(id: "GOLTS.IS", symbol: "GOLTS", name: "Göltaş Çimento",    sector: "Çimento"),
        Stock(id: "BOLUC.IS", symbol: "BOLUC", name: "Bolu Çimento",       sector: "Çimento"),
        Stock(id: "BSOKE.IS", symbol: "BSOKE", name: "Batısöke Çimento",  sector: "Çimento"),
        Stock(id: "MRDIN.IS", symbol: "MRDIN", name: "Mardin Çimento",     sector: "Çimento"),
        Stock(id: "NUHCM.IS", symbol: "NUHCM", name: "Nuh Çimento",       sector: "Çimento"),
        Stock(id: "UNYEC.IS", symbol: "UNYEC", name: "Ünye Çimento",      sector: "Çimento"),
        Stock(id: "BTCIM.IS", symbol: "BTCIM", name: "Batı Çimento",      sector: "Çimento"),
        Stock(id: "AFKUR.IS", symbol: "AFKUR", name: "Afyon Çimento",     sector: "Çimento"),
        Stock(id: "KONYA.IS", symbol: "KONYA", name: "Konya Çimento",     sector: "Çimento"),
        Stock(id: "BUCIM.IS", symbol: "BUCIM", name: "Bursa Çimento",     sector: "Çimento"),
        Stock(id: "OYAKC.IS", symbol: "OYAKC", name: "Oyak Çimento",      sector: "Çimento"),
        Stock(id: "ASLAN.IS", symbol: "ASLAN", name: "Aslan Çimento",     sector: "Çimento"),
        Stock(id: "EGPRO.IS", symbol: "EGPRO", name: "Ege Profil",        sector: "Çimento"),
        Stock(id: "IZOCM.IS", symbol: "IZOCM", name: "İzocam",            sector: "İnşaat"),

        // MARK: - GYO & İnşaat
        Stock(id: "EKGYO.IS", symbol: "EKGYO", name: "Emlak Konut GYO",   sector: "GYO"),
        Stock(id: "ISGYO.IS", symbol: "ISGYO", name: "İş GYO",            sector: "GYO"),
        Stock(id: "TRGYO.IS", symbol: "TRGYO", name: "Torunlar GYO",      sector: "GYO"),
        Stock(id: "SNGYO.IS", symbol: "SNGYO", name: "Sinpaş GYO",        sector: "GYO"),
        Stock(id: "HLGYO.IS", symbol: "HLGYO", name: "Halk GYO",          sector: "GYO"),
        Stock(id: "VAKGYO.IS",symbol: "VAKGYO",name: "Vakıf GYO",         sector: "GYO"),
        Stock(id: "SRVGY.IS", symbol: "SRVGY", name: "Servet GYO",        sector: "GYO"),
        Stock(id: "OZGYO.IS", symbol: "OZGYO", name: "Özderici GYO",      sector: "GYO"),
        Stock(id: "MSGYO.IS", symbol: "MSGYO", name: "Martı GYO",         sector: "GYO"),
        Stock(id: "NUGYO.IS", symbol: "NUGYO", name: "Nurol GYO",         sector: "GYO"),
        Stock(id: "PEKGY.IS", symbol: "PEKGY", name: "Peker GYO",         sector: "GYO"),
        Stock(id: "AGYO.IS",  symbol: "AGYO",  name: "Atakule GYO",       sector: "GYO"),
        Stock(id: "ATAGY.IS", symbol: "ATAGY", name: "Ata GYO",           sector: "GYO"),
        Stock(id: "ALGYO.IS", symbol: "ALGYO", name: "Alarko GYO",        sector: "GYO"),
        Stock(id: "AKSGY.IS", symbol: "AKSGY", name: "Akiş GYO",          sector: "GYO"),
        Stock(id: "IHLGM.IS", symbol: "IHLGM", name: "İhlas Gayrimenkul", sector: "GYO"),
        Stock(id: "DNISI.IS", symbol: "DNISI", name: "Deniz GYO",         sector: "GYO"),
        Stock(id: "ENKAI.IS", symbol: "ENKAI", name: "Enka İnşaat",       sector: "İnşaat"),
        Stock(id: "DOGUB.IS", symbol: "DOGUB", name: "Doğuş İnşaat",     sector: "İnşaat"),

        // MARK: - Perakende
        Stock(id: "BIMAS.IS", symbol: "BIMAS", name: "BİM Mağazaları",    sector: "Perakende"),
        Stock(id: "MGROS.IS", symbol: "MGROS", name: "Migros",             sector: "Perakende"),
        Stock(id: "SOKM.IS",  symbol: "SOKM",  name: "Şok Marketler",     sector: "Perakende"),
        Stock(id: "BIZIM.IS", symbol: "BIZIM", name: "Bizim Toptan",       sector: "Perakende"),
        Stock(id: "MAVI.IS",  symbol: "MAVI",  name: "Mavi Giyim",        sector: "Perakende"),
        Stock(id: "BOYP.IS",  symbol: "BOYP",  name: "Boyner Perakende",  sector: "Perakende"),
        Stock(id: "VAKKO.IS", symbol: "VAKKO", name: "Vakko Tekstil",      sector: "Perakende"),
        Stock(id: "DESA.IS",  symbol: "DESA",  name: "Desa Deri",          sector: "Perakende"),
        Stock(id: "TKNSA.IS", symbol: "TKNSA", name: "Teknosa",            sector: "Perakende"),

        // MARK: - Gıda & İçecek
        Stock(id: "ULKER.IS", symbol: "ULKER", name: "Ülker Bisküvi",     sector: "Gıda"),
        Stock(id: "TATGD.IS", symbol: "TATGD", name: "Tat Gıda",          sector: "Gıda"),
        Stock(id: "AEFES.IS", symbol: "AEFES", name: "Anadolu Efes",      sector: "Gıda"),
        Stock(id: "CCOLA.IS", symbol: "CCOLA", name: "Coca-Cola İçecek",  sector: "Gıda"),
        Stock(id: "KRVGD.IS", symbol: "KRVGD", name: "Kervan Gıda",       sector: "Gıda"),
        Stock(id: "PNSUT.IS", symbol: "PNSUT", name: "Pınar Süt",         sector: "Gıda"),
        Stock(id: "KERVT.IS", symbol: "KERVT", name: "Kervansaray Tatl.", sector: "Gıda"),
        Stock(id: "TUKAS.IS", symbol: "TUKAS", name: "Tukaş",             sector: "Gıda"),
        Stock(id: "BANVT.IS", symbol: "BANVT", name: "Banvit",            sector: "Gıda"),
        Stock(id: "SELGT.IS", symbol: "SELGT", name: "Selçuk Gıda",      sector: "Gıda"),
        Stock(id: "TBORG.IS", symbol: "TBORG", name: "Türk Tuborg",       sector: "Gıda"),
        Stock(id: "KNFRT.IS", symbol: "KNFRT", name: "Konfrut",           sector: "Gıda"),
        Stock(id: "DARDL.IS", symbol: "DARDL", name: "Dardanel",          sector: "Gıda"),
        Stock(id: "ERSU.IS",  symbol: "ERSU",  name: "Ersu Meyve",        sector: "Gıda"),
        Stock(id: "KENT.IS",  symbol: "KENT",  name: "Kent Gıda",         sector: "Gıda"),
        Stock(id: "PETUN.IS", symbol: "PETUN", name: "Pınar Et ve Un",   sector: "Gıda"),

        // MARK: - Tekstil
        Stock(id: "KORDS.IS", symbol: "KORDS", name: "Kordsa",            sector: "Tekstil"),
        Stock(id: "ARSAN.IS", symbol: "ARSAN", name: "Arsan Tekstil",     sector: "Tekstil"),
        Stock(id: "BOSSA.IS", symbol: "BOSSA", name: "Bossa",             sector: "Tekstil"),
        Stock(id: "SKTAS.IS", symbol: "SKTAS", name: "Söktaş",           sector: "Tekstil"),
        Stock(id: "YATAS.IS", symbol: "YATAS", name: "Yataş",            sector: "Tekstil"),
        Stock(id: "YUNSA.IS", symbol: "YUNSA", name: "Yünsa",            sector: "Tekstil"),
        Stock(id: "LUKSK.IS", symbol: "LUKSK", name: "Lüks Kadife",      sector: "Tekstil"),
        Stock(id: "FLAP.IS",  symbol: "FLAP",  name: "Flap Kongre",       sector: "Tekstil"),
        Stock(id: "KAPLM.IS", symbol: "KAPLM", name: "Kaplamin Ambalaj", sector: "Tekstil"),

        // MARK: - Telekomünikasyon
        Stock(id: "TCELL.IS", symbol: "TCELL", name: "Turkcell",          sector: "Telekomünikasyon"),
        Stock(id: "TTKOM.IS", symbol: "TTKOM", name: "Türk Telekom",     sector: "Telekomünikasyon"),

        // MARK: - Sigorta & Finans
        Stock(id: "AKGRT.IS", symbol: "AKGRT", name: "Aksigorta",        sector: "Sigorta"),
        Stock(id: "ANHYT.IS", symbol: "ANHYT", name: "Anadolu Hayat",    sector: "Sigorta"),
        Stock(id: "RAYSG.IS", symbol: "RAYSG", name: "Ray Sigorta",      sector: "Sigorta"),
        Stock(id: "ANSGR.IS", symbol: "ANSGR", name: "Anadolu Sigorta",  sector: "Sigorta"),
        Stock(id: "GUSGR.IS", symbol: "GUSGR", name: "Güneş Sigorta",   sector: "Sigorta"),
        Stock(id: "TURSG.IS", symbol: "TURSG", name: "Türk Sigorta",     sector: "Sigorta"),
        Stock(id: "ISFIN.IS", symbol: "ISFIN", name: "İş Finansal Kiralama", sector: "Finans"),
        Stock(id: "GARFA.IS", symbol: "GARFA", name: "Garanti Faktoring", sector: "Finans"),
        Stock(id: "LIDER.IS", symbol: "LIDER", name: "Lider Faktoring",   sector: "Finans"),
        Stock(id: "ISYAT.IS", symbol: "ISYAT", name: "İş Yatırım",       sector: "Finans"),
        Stock(id: "ATLAS.IS", symbol: "ATLAS", name: "Atlas Menkul",      sector: "Finans"),

        // MARK: - Turizm & Otel
        Stock(id: "MAALT.IS", symbol: "MAALT", name: "Marmaris Altınyunus", sector: "Turizm"),
        Stock(id: "NTTUR.IS", symbol: "NTTUR", name: "Net Turizm",         sector: "Turizm"),
        Stock(id: "METUR.IS", symbol: "METUR", name: "Metemtur",           sector: "Turizm"),
        Stock(id: "PKENT.IS", symbol: "PKENT", name: "Petrokent Turizm",   sector: "Turizm"),
        Stock(id: "FVORI.IS", symbol: "FVORI", name: "Favori Dinlenme",    sector: "Turizm"),

        // MARK: - Madencilik
        Stock(id: "KOZAL.IS", symbol: "KOZAL", name: "Koza Altın",        sector: "Madencilik"),
        Stock(id: "KOZAA.IS", symbol: "KOZAA", name: "Koza Madencilik A", sector: "Madencilik"),
        Stock(id: "IPEKE.IS", symbol: "IPEKE", name: "İpek Doğal Enerji", sector: "Madencilik"),
        Stock(id: "MNKAY.IS", symbol: "MNKAY", name: "Minkay",            sector: "Madencilik"),

        // MARK: - Medya & Spor
        Stock(id: "BJKAS.IS", symbol: "BJKAS", name: "Beşiktaş",         sector: "Spor"),
        Stock(id: "FENER.IS", symbol: "FENER", name: "Fenerbahçe",       sector: "Spor"),
        Stock(id: "GSRAY.IS", symbol: "GSRAY", name: "Galatasaray",       sector: "Spor"),
        Stock(id: "TSPOR.IS", symbol: "TSPOR", name: "Trabzonspor",       sector: "Spor"),
        Stock(id: "HURGZ.IS", symbol: "HURGZ", name: "Hürriyet",         sector: "Medya"),
        Stock(id: "IHYAY.IS", symbol: "IHYAY", name: "İhlas Yayın",      sector: "Medya"),

        // MARK: - Elektrik & Kablo
        Stock(id: "PNLSN.IS", symbol: "PNLSN", name: "Panelsan",         sector: "Elektrik"),

        // MARK: - Tarım
        Stock(id: "ALYAG.IS", symbol: "ALYAG", name: "Alaçatı Yağ",       sector: "Tarım"),
        Stock(id: "OYLUM.IS", symbol: "OYLUM", name: "Oylum Sınai Yatırım", sector: "Tarım"),
        Stock(id: "YYLGD.IS", symbol: "YYLGD", name: "Yayla Agro Gıda",   sector: "Tarım"),

        // MARK: - Ek Sanayi & Üretim
        Stock(id: "ADEL.IS",  symbol: "ADEL",  name: "Adel Kalemcilik",      sector: "Sanayi"),
        Stock(id: "MAKIM.IS", symbol: "MAKIM", name: "Makine Takım End.",    sector: "Sanayi"),
        Stock(id: "MEGMT.IS", symbol: "MEGMT", name: "Megmetal Makina",      sector: "Sanayi"),
        Stock(id: "SAMAT.IS", symbol: "SAMAT", name: "Samat Makina",         sector: "Sanayi"),
        Stock(id: "GEREL.IS", symbol: "GEREL", name: "Gersan Elektrik",      sector: "Sanayi"),
        Stock(id: "OSMEN.IS", symbol: "OSMEN", name: "Osman Endüstri",       sector: "Sanayi"),
        Stock(id: "OSTIM.IS", symbol: "OSTIM", name: "Ostim Endüstriyel",   sector: "Sanayi"),
        Stock(id: "ACSEL.IS", symbol: "ACSEL", name: "Acıselsan Kablo",      sector: "Sanayi"),
        Stock(id: "ERBOS.IS", symbol: "ERBOS", name: "Erbosan Erciyas Boru", sector: "Metal"),
        Stock(id: "GENTS.IS", symbol: "GENTS", name: "Gentaş Metal San.",    sector: "Metal"),
        Stock(id: "TMSN.IS",  symbol: "TMSN",  name: "Tomsan Kablo",         sector: "Metal"),
        Stock(id: "BRVAG.IS", symbol: "BRVAG", name: "Birvagas",             sector: "Metal"),
        Stock(id: "ALVES.IS", symbol: "ALVES", name: "Alves Elektromekanik", sector: "Metal"),
        Stock(id: "GEDZA.IS", symbol: "GEDZA", name: "Gediz Ambalaj",        sector: "Metal"),

        // MARK: - Ek Tekstil
        Stock(id: "EDIP.IS",  symbol: "EDIP",  name: "Edip İplik",           sector: "Tekstil"),
        Stock(id: "MNDRS.IS", symbol: "MNDRS", name: "Menderes Tekstil",     sector: "Tekstil"),
        Stock(id: "ROYAL.IS", symbol: "ROYAL", name: "Royal Halı",           sector: "Tekstil"),
        Stock(id: "SONS.IS",  symbol: "SONS",  name: "Sönmez Filament",      sector: "Tekstil"),
        Stock(id: "ASTER.IS", symbol: "ASTER", name: "Aster Tekstil",        sector: "Tekstil"),
        Stock(id: "DMSAS.IS", symbol: "DMSAS", name: "Demisaş Döküm",       sector: "Tekstil"),

        // MARK: - Ek Kimya & Boya
        Stock(id: "DYOBY.IS", symbol: "DYOBY", name: "DYO Boya",             sector: "Kimya"),
        Stock(id: "MRSHL.IS", symbol: "MRSHL", name: "Marshall Boya",        sector: "Kimya"),
        Stock(id: "PIMAS.IS", symbol: "PIMAS", name: "Pimas Plastik",        sector: "Kimya"),
        Stock(id: "ORCAY.IS", symbol: "ORCAY", name: "Orcay Organik",        sector: "Kimya"),
        Stock(id: "HUNER.IS", symbol: "HUNER", name: "Hüner Kimya",          sector: "Kimya"),

        // MARK: - Ek Enerji & Elektrik
        Stock(id: "ASTOR.IS", symbol: "ASTOR", name: "Astor Enerji",         sector: "Enerji"),
        Stock(id: "AYDEM.IS", symbol: "AYDEM", name: "Aydem Enerji",         sector: "Enerji"),
        Stock(id: "MANAS.IS", symbol: "MANAS", name: "Manas Enerji",         sector: "Enerji"),
        Stock(id: "GESAN.IS", symbol: "GESAN", name: "Gesan Enerji Sis.",    sector: "Enerji"),
        Stock(id: "MIPAZ.IS", symbol: "MIPAZ", name: "Mipaz Petrol",         sector: "Enerji"),
        Stock(id: "AKFYE.IS", symbol: "AKFYE", name: "Akfen Yenilenebilir",  sector: "Enerji"),
        Stock(id: "ULUSE.IS", symbol: "ULUSE", name: "Ulusoy Elektrik",      sector: "Elektrik"),
        Stock(id: "MAGEN.IS", symbol: "MAGEN", name: "Mavi Gök Enerji",      sector: "Enerji"),
        Stock(id: "SEYKM.IS", symbol: "SEYKM", name: "Seykum",               sector: "Enerji"),
        Stock(id: "EUREN.IS", symbol: "EUREN", name: "Euro Enerji",           sector: "Enerji"),
        Stock(id: "DENGE.IS", symbol: "DENGE", name: "Denge Enerji",          sector: "Enerji"),

        // MARK: - Ek Teknoloji & Bilişim
        Stock(id: "ARMDA.IS", symbol: "ARMDA", name: "Armada Bilgisayar",    sector: "Teknoloji"),
        Stock(id: "FONET.IS", symbol: "FONET", name: "Fonet Bilişim",        sector: "Teknoloji"),
        Stock(id: "FORTE.IS", symbol: "FORTE", name: "Forte Bilişim",        sector: "Teknoloji"),
        Stock(id: "INVEO.IS", symbol: "INVEO", name: "İnveo Portföy",        sector: "Teknoloji"),
        Stock(id: "KFEIN.IS", symbol: "KFEIN", name: "Kafein Yazılım",       sector: "Teknoloji"),
        Stock(id: "MTRKS.IS", symbol: "MTRKS", name: "Matreks Bilişim",      sector: "Teknoloji"),
        Stock(id: "PENTA.IS", symbol: "PENTA", name: "Penta Teknoloji",      sector: "Teknoloji"),
        Stock(id: "PKART.IS", symbol: "PKART", name: "Plastikkart",          sector: "Teknoloji"),
        Stock(id: "ARDYZ.IS", symbol: "ARDYZ", name: "Ardıç Yazılım",       sector: "Teknoloji"),
        Stock(id: "DESPC.IS", symbol: "DESPC", name: "Despec Bilgisayar",   sector: "Teknoloji"),
        Stock(id: "MOBTL.IS", symbol: "MOBTL", name: "Mobil Teknoloji",      sector: "Teknoloji"),
        Stock(id: "ARENA.IS", symbol: "ARENA", name: "Arena Bilgisayar",     sector: "Teknoloji"),

        // MARK: - Ek Sağlık
        Stock(id: "LKMNH.IS", symbol: "LKMNH", name: "Lokman Hekim",         sector: "Sağlık"),
        Stock(id: "GLBMD.IS", symbol: "GLBMD", name: "Global Medikal",       sector: "Sağlık"),
        Stock(id: "MEDTR.IS", symbol: "MEDTR", name: "Meditera Tıbbi",       sector: "Sağlık"),
        Stock(id: "BIGEN.IS", symbol: "BIGEN", name: "Bilim Ecza Deposu",   sector: "İlaç"),
        Stock(id: "ADESE.IS", symbol: "ADESE", name: "Adese Alışveriş",     sector: "Sağlık"),

        // MARK: - Ek Perakende & Gıda
        Stock(id: "METRO.IS", symbol: "METRO", name: "Metro Ticaret",        sector: "Perakende"),
        Stock(id: "KILER.IS", symbol: "KILER", name: "Kiler Alışveriş",     sector: "Perakende"),
        Stock(id: "KOFAZ.IS", symbol: "KOFAZ", name: "Kofaz Gıda",          sector: "Gıda"),
        Stock(id: "ARASE.IS", symbol: "ARASE", name: "Araş Gıda",           sector: "Gıda"),
        Stock(id: "OLMKS.IS", symbol: "OLMKS", name: "Olmuksa Int. Paper",  sector: "Gıda"),

        // MARK: - Ek GYO
        Stock(id: "AKFGY.IS", symbol: "AKFGY", name: "Akfen GYO",           sector: "GYO"),
        Stock(id: "AKMGY.IS", symbol: "AKMGY", name: "Akmerkez GYO",        sector: "GYO"),
        Stock(id: "MRGYO.IS", symbol: "MRGYO", name: "Merkez GYO",          sector: "GYO"),
        Stock(id: "RYGYO.IS", symbol: "RYGYO", name: "Rya GYO",             sector: "GYO"),
        Stock(id: "VEGYO.IS", symbol: "VEGYO", name: "Vega GYO",            sector: "GYO"),
        Stock(id: "ZRGYO.IS", symbol: "ZRGYO", name: "Ziraat GYO",          sector: "GYO"),
        Stock(id: "YKGYO.IS", symbol: "YKGYO", name: "Yapı Kredi GYO",     sector: "GYO"),
        Stock(id: "DZGYO.IS", symbol: "DZGYO", name: "Denizbank GYO",       sector: "GYO"),
        Stock(id: "OYGYO.IS", symbol: "OYGYO", name: "Oyaş GYO",            sector: "GYO"),
        Stock(id: "ESCAR.IS", symbol: "ESCAR", name: "Escort Hizmetleri",   sector: "İnşaat"),
        Stock(id: "YKONT.IS", symbol: "YKONT", name: "Yüksel Proje",        sector: "İnşaat"),
        Stock(id: "INTEM.IS", symbol: "INTEM", name: "İntema Yapı",          sector: "İnşaat"),
        Stock(id: "VARYA.IS", symbol: "VARYA", name: "Varyap",              sector: "İnşaat"),

        // MARK: - Ek Cam & Seramik
        Stock(id: "CANTR.IS", symbol: "CANTR", name: "Çanakkale Seramik",  sector: "Seramik"),
        Stock(id: "KTSKE.IS", symbol: "KTSKE", name: "Kütahya Seramik",    sector: "Seramik"),
        Stock(id: "EGSER.IS", symbol: "EGSER", name: "Ege Seramik",        sector: "Seramik"),
        Stock(id: "USAK.IS",  symbol: "USAK",  name: "Uşak Seramik",       sector: "Seramik"),
        Stock(id: "KBORU.IS", symbol: "KBORU", name: "Krone Boru",         sector: "Cam"),

        // MARK: - Ek Holding & Finans
        Stock(id: "GSDHO.IS", symbol: "GSDHO", name: "GSD Holding",         sector: "Holding"),
        Stock(id: "MARKA.IS", symbol: "MARKA", name: "Marka Yatırım Hld.",  sector: "Holding"),
        Stock(id: "HTTBT.IS", symbol: "HTTBT", name: "Hattat Holding",       sector: "Holding"),
        Stock(id: "KCFIN.IS", symbol: "KCFIN", name: "Koç Finansman",       sector: "Finans"),
        Stock(id: "SEKFK.IS", symbol: "SEKFK", name: "Şeker Faktoring",    sector: "Finans"),
        Stock(id: "QNBFL.IS", symbol: "QNBFL", name: "QNB Finansleasing",  sector: "Finans"),
        Stock(id: "VAKFN.IS", symbol: "VAKFN", name: "Vakıf Fin. Kiralama", sector: "Finans"),
        Stock(id: "YKFIN.IS", symbol: "YKFIN", name: "YKF Finansal Kir.",   sector: "Finans"),
        Stock(id: "TRILC.IS", symbol: "TRILC", name: "Türkiye İş Leasing", sector: "Finans"),
        Stock(id: "GEDIK.IS", symbol: "GEDIK", name: "Gedik Yatırım",       sector: "Finans"),
        Stock(id: "AGESA.IS", symbol: "AGESA", name: "AGesa Sigorta",        sector: "Sigorta"),

        // MARK: - Ek Turizm
        Stock(id: "MERIT.IS", symbol: "MERIT", name: "Merit Turizm",        sector: "Turizm"),
        Stock(id: "AYCES.IS", symbol: "AYCES", name: "Altınyunus Çeşme",   sector: "Turizm"),
        Stock(id: "CRFSA.IS", symbol: "CRFSA", name: "Carrefour SA",        sector: "Turizm"),
        Stock(id: "SEDEN.IS", symbol: "SEDEN", name: "Sedef Tersanesi",     sector: "Turizm"),

        // MARK: - Ek Madencilik
        Stock(id: "GMTAS.IS", symbol: "GMTAS", name: "Gümüştaş Madencilik", sector: "Madencilik"),
        Stock(id: "SELGD.IS", symbol: "SELGD", name: "Sel Girişim",         sector: "Madencilik"),

        // MARK: - Kağıt & Ambalaj
        Stock(id: "KARTN.IS", symbol: "KARTN", name: "Kartonsan",           sector: "Kağıt"),
        Stock(id: "BAKAB.IS", symbol: "BAKAB", name: "Bak Ambalaj",         sector: "Kağıt"),
        Stock(id: "TEZOL.IS", symbol: "TEZOL", name: "Tezol Kağıt",        sector: "Kağıt"),
        Stock(id: "SNPAM.IS", symbol: "SNPAM", name: "Şenpazar Ambalaj",   sector: "Kağıt"),

        // MARK: - Lojistik & Denizcilik
        Stock(id: "GSDDE.IS", symbol: "GSDDE", name: "GSD Denizcilik",      sector: "Denizcilik"),
        Stock(id: "SEDEF.IS", symbol: "SEDEF", name: "Sedef Tersanesi",     sector: "Denizcilik"),
        Stock(id: "ULASL.IS", symbol: "ULASL", name: "Ulaşlar Turizm",     sector: "Lojistik"),
        Stock(id: "AVTUR.IS", symbol: "AVTUR", name: "Avrasya Petrol",      sector: "Lojistik"),
        Stock(id: "KONTR.IS", symbol: "KONTR", name: "Kontrolmatik",        sector: "Lojistik"),
        Stock(id: "MEPET.IS", symbol: "MEPET", name: "Mepet Metro",         sector: "Lojistik"),

        // MARK: - Otomotiv (Ek)
        Stock(id: "RENTA.IS", symbol: "RENTA", name: "Rentaş",              sector: "Otomotiv"),

        // MARK: - Elektronik (Ek)
        Stock(id: "SIMGE.IS", symbol: "SIMGE", name: "Simge Reklam",        sector: "Elektronik"),

        // MARK: - Bankacılık (Ek-2)
        Stock(id: "ISKUR.IS", symbol: "ISKUR", name: "Türkiye İş Bankası", sector: "Bankacılık"),
        Stock(id: "KLNMA.IS", symbol: "KLNMA", name: "Türkiye Kalkınma Ve Yatırım Bankası", sector: "Bankacılık"),

        // MARK: - Çimento (Ek-2)
        Stock(id: "AFYON.IS", symbol: "AFYON", name: "Afyon Çimento", sector: "Çimento"),
        Stock(id: "BASCM.IS", symbol: "BASCM", name: "Baştaş Başkent Çimento", sector: "Çimento"),
        Stock(id: "BOBET.IS", symbol: "BOBET", name: "Boğaziçi Beton", sector: "Çimento"),
        Stock(id: "CMBTN.IS", symbol: "CMBTN", name: "Çimbeton Hazırbeton", sector: "Çimento"),
        Stock(id: "CMENT.IS", symbol: "CMENT", name: "Çimentaş İzmir Çimento", sector: "Çimento"),

        // MARK: - Enerji (Ek-2)
        Stock(id: "A1YEN.IS", symbol: "A1YEN", name: "A1 Yenilenebilir Enerji", sector: "Enerji"),
        Stock(id: "AHGAZ.IS", symbol: "AHGAZ", name: "Ahlatcı Doğal Gaz", sector: "Enerji"),
        Stock(id: "AKSUE.IS", symbol: "AKSUE", name: "Aksu Enerji", sector: "Enerji"),
        Stock(id: "ARFYE.IS", symbol: "ARFYE", name: "ARF Bio Yenilenebilir Enerji", sector: "Enerji"),
        Stock(id: "BASGZ.IS", symbol: "BASGZ", name: "Başkent Doğalgaz Dağıtım", sector: "Enerji"),
        Stock(id: "BESTE.IS", symbol: "BESTE", name: "Best Brands Enerji", sector: "Enerji"),
        Stock(id: "CATES.IS", symbol: "CATES", name: "Cates Elektrik Üretim", sector: "Enerji"),
        Stock(id: "CONSE.IS", symbol: "CONSE", name: "Consus Enerji", sector: "Enerji"),
        Stock(id: "ECOGR.IS", symbol: "ECOGR", name: "Ecogreen Enerji Holding", sector: "Enerji"),
        Stock(id: "ENERY.IS", symbol: "ENERY", name: "Enerya Enerji", sector: "Enerji"),
        Stock(id: "ENJSA.IS", symbol: "ENJSA", name: "Enerjisa Enerji", sector: "Enerji"),
        Stock(id: "ENTRA.IS", symbol: "ENTRA", name: "IC Enterra Yenilenebilir Enerji", sector: "Enerji"),
        Stock(id: "ESEN.IS",  symbol: "ESEN",  name: "Esenboğa Elektrik Üretim", sector: "Enerji"),
        Stock(id: "IZENR.IS", symbol: "IZENR", name: "İzdemir Enerji", sector: "Enerji"),
        Stock(id: "MOGAN.IS", symbol: "MOGAN", name: "Mogan Enerji", sector: "Enerji"),
        Stock(id: "NTGAZ.IS", symbol: "NTGAZ", name: "Naturelgaz", sector: "Enerji"),
        Stock(id: "PAMEL.IS", symbol: "PAMEL", name: "Pamel Yenilenebilir Elektrik", sector: "Enerji"),
        Stock(id: "TATEN.IS", symbol: "TATEN", name: "Tatlıpınar Enerji", sector: "Enerji"),
        Stock(id: "TRCAS.IS", symbol: "TRCAS", name: "Turcas Petrol", sector: "Enerji"),
        Stock(id: "TRENJ.IS", symbol: "TRENJ", name: "TR Doğal Enerji Kaynakları", sector: "Enerji"),
        Stock(id: "YEOTK.IS", symbol: "YEOTK", name: "Yeo Teknoloji Enerji", sector: "Enerji"),

        // MARK: - Finans (Ek-2)
        Stock(id: "A1CAP.IS", symbol: "A1CAP", name: "A1 Capital", sector: "Finans"),
        Stock(id: "BRKVY.IS", symbol: "BRKVY", name: "Birikim Varlık Yönetim", sector: "Finans"),
        Stock(id: "CRDFA.IS", symbol: "CRDFA", name: "Creditwest Faktoring", sector: "Finans"),
        Stock(id: "DSTKF.IS", symbol: "DSTKF", name: "Destek Faktoring", sector: "Finans"),
        Stock(id: "ENPRA.IS", symbol: "ENPRA", name: "Enpara Bank", sector: "Finans"),
        Stock(id: "GLCVY.IS", symbol: "GLCVY", name: "Gelecek Varlık Yönetimi", sector: "Finans"),
        Stock(id: "GRNYO.IS", symbol: "GRNYO", name: "Garanti Yatırım Ortaklığı", sector: "Finans"),
        Stock(id: "HDFGS.IS", symbol: "HDFGS", name: "Hedef Girişim Sermayesi", sector: "Finans"),
        Stock(id: "HUBVC.IS", symbol: "HUBVC", name: "Hub Girişim Sermayesi", sector: "Finans"),
        Stock(id: "ICUGS.IS", symbol: "ICUGS", name: "ICU Girişim Sermayesi", sector: "Finans"),
        Stock(id: "INFO.IS",  symbol: "INFO",  name: "İnfo Yatırım", sector: "Finans"),
        Stock(id: "ISGSY.IS", symbol: "ISGSY", name: "İş Girişim Sermayesi", sector: "Finans"),
        Stock(id: "ISMEN.IS", symbol: "ISMEN", name: "İş Yatırım Menkul", sector: "Finans"),
        Stock(id: "KUYAS.IS", symbol: "KUYAS", name: "Kuyaş Yatırım", sector: "Finans"),
        Stock(id: "LIDFA.IS", symbol: "LIDFA", name: "Lider Faktoring", sector: "Finans"),
        Stock(id: "OYAYO.IS", symbol: "OYAYO", name: "Oyak Yatırım Ortaklığı", sector: "Finans"),
        Stock(id: "OYYAT.IS", symbol: "OYYAT", name: "Oyak Yatırım Menkul", sector: "Finans"),
        Stock(id: "PRDGS.IS", symbol: "PRDGS", name: "Pardus Girişim Sermayesi", sector: "Finans"),
        Stock(id: "QNBFK.IS", symbol: "QNBFK", name: "QNB Finansal Kiralama", sector: "Finans"),
        Stock(id: "QNBTR.IS", symbol: "QNBTR", name: "QNB Bank", sector: "Finans"),
        Stock(id: "SKYMD.IS", symbol: "SKYMD", name: "Şeker Yatırım Menkul", sector: "Finans"),
        Stock(id: "TERA.IS",  symbol: "TERA",  name: "Tera Yatırım", sector: "Finans"),
        Stock(id: "ULUFA.IS", symbol: "ULUFA", name: "Ulusal Faktoring", sector: "Finans"),
        Stock(id: "VAKFA.IS", symbol: "VAKFA", name: "Vakıf Faktoring", sector: "Finans"),
        Stock(id: "VERTU.IS", symbol: "VERTU", name: "Verusaturk Girişim Sermayesi", sector: "Finans"),
        Stock(id: "VKFYO.IS", symbol: "VKFYO", name: "Vakıf Menkul Kıymet", sector: "Finans"),
        Stock(id: "ETYAT.IS", symbol: "ETYAT", name: "Euro Trend Yatırım Ortaklığı", sector: "Finans"),
        Stock(id: "EUKYO.IS", symbol: "EUKYO", name: "Euro Kapital Yatırım Ortaklığı", sector: "Finans"),
        Stock(id: "EUYO.IS",  symbol: "EUYO",  name: "Euro Menkul Kıymet Yatırım Ortaklığı", sector: "Finans"),
        Stock(id: "BORLS.IS", symbol: "BORLS", name: "Borlease Otomotiv", sector: "Finans"),
        Stock(id: "BULGS.IS", symbol: "BULGS", name: "Bulls Girişim Sermayesi", sector: "Finans"),

        // MARK: - GYO (Ek-2)
        Stock(id: "AAGYO.IS", symbol: "AAGYO", name: "Ağaoğlu Avrasya GYO", sector: "GYO"),
        Stock(id: "ADGYO.IS", symbol: "ADGYO", name: "Adra GYO", sector: "GYO"),
        Stock(id: "AHSGY.IS", symbol: "AHSGY", name: "Ahes GYO", sector: "GYO"),
        Stock(id: "ASGYO.IS", symbol: "ASGYO", name: "Asce GYO", sector: "GYO"),
        Stock(id: "AVGYO.IS", symbol: "AVGYO", name: "Avrasya GYO", sector: "GYO"),
        Stock(id: "AVPGY.IS", symbol: "AVPGY", name: "Avrupakent GYO", sector: "GYO"),
        Stock(id: "BEGYO.IS", symbol: "BEGYO", name: "Batı Ege GYO", sector: "GYO"),
        Stock(id: "DAPGM.IS", symbol: "DAPGM", name: "DAP Gayrimenkul", sector: "GYO"),
        Stock(id: "DGGYO.IS", symbol: "DGGYO", name: "Doğuş GYO", sector: "GYO"),
        Stock(id: "EGEGY.IS", symbol: "EGEGY", name: "Egeyapı Avrupa GYO", sector: "GYO"),
        Stock(id: "EYGYO.IS", symbol: "EYGYO", name: "EYG GYO", sector: "GYO"),
        Stock(id: "IDGYO.IS", symbol: "IDGYO", name: "İdealist GYO", sector: "GYO"),
        Stock(id: "KGYO.IS",  symbol: "KGYO",  name: "Koray GYO", sector: "GYO"),
        Stock(id: "KLGYO.IS", symbol: "KLGYO", name: "Kiler GYO", sector: "GYO"),
        Stock(id: "KRGYO.IS", symbol: "KRGYO", name: "Körfez GYO", sector: "GYO"),
        Stock(id: "KZBGY.IS", symbol: "KZBGY", name: "Kızılbük GYO", sector: "GYO"),
        Stock(id: "KZGYO.IS", symbol: "KZGYO", name: "Kuzugrup GYO", sector: "GYO"),
        Stock(id: "LXGYO.IS", symbol: "LXGYO", name: "Luxera GYO", sector: "GYO"),
        Stock(id: "MHRGY.IS", symbol: "MHRGY", name: "MHR GYO", sector: "GYO"),
        Stock(id: "OZKGY.IS", symbol: "OZKGY", name: "Özak GYO", sector: "GYO"),
        Stock(id: "PAGYO.IS", symbol: "PAGYO", name: "Panora GYO", sector: "GYO"),
        Stock(id: "PSGYO.IS", symbol: "PSGYO", name: "Pasifik GYO", sector: "GYO"),
        Stock(id: "RGYAS.IS", symbol: "RGYAS", name: "Rönesans Gayrimenkul", sector: "GYO"),
        Stock(id: "SEGYO.IS", symbol: "SEGYO", name: "Şeker GYO", sector: "GYO"),
        Stock(id: "SURGY.IS", symbol: "SURGY", name: "Sur Tatil Evleri GYO", sector: "GYO"),
        Stock(id: "SVGYO.IS", symbol: "SVGYO", name: "Savur GYO", sector: "GYO"),
        Stock(id: "TDGYO.IS", symbol: "TDGYO", name: "Trend GYO", sector: "GYO"),
        Stock(id: "TSGYO.IS", symbol: "TSGYO", name: "TSKB GYO", sector: "GYO"),
        Stock(id: "TURGG.IS", symbol: "TURGG", name: "Türker Proje Gayrimenkul", sector: "GYO"),
        Stock(id: "UFUK.IS",  symbol: "UFUK",  name: "Ufuk GYO", sector: "GYO"),
        Stock(id: "VKGYO.IS", symbol: "VKGYO", name: "Vakıf GYO", sector: "GYO"),
        Stock(id: "VRGYO.IS", symbol: "VRGYO", name: "Vera Konsept GYO", sector: "GYO"),
        Stock(id: "YGGYO.IS", symbol: "YGGYO", name: "Yeni Gimat GYO", sector: "GYO"),
        Stock(id: "ZERGY.IS", symbol: "ZERGY", name: "Zeray GYO", sector: "GYO"),
        Stock(id: "ZGYO.IS",  symbol: "ZGYO",  name: "Z GYO", sector: "GYO"),

        // MARK: - Holding (Ek-2)
        Stock(id: "ENDAE.IS", symbol: "ENDAE", name: "Enda Enerji Holding", sector: "Holding"),
        Stock(id: "EUHOL.IS", symbol: "EUHOL", name: "Euro Yatırım Holding", sector: "Holding"),
        Stock(id: "GLRYH.IS", symbol: "GLRYH", name: "Güler Yatırım Holding", sector: "Holding"),
        Stock(id: "HEDEF.IS", symbol: "HEDEF", name: "Hedef Holding", sector: "Holding"),
        Stock(id: "INVES.IS", symbol: "INVES", name: "Investco Holding", sector: "Holding"),
        Stock(id: "MARMR.IS", symbol: "MARMR", name: "Marmara Holding", sector: "Holding"),
        Stock(id: "TEHOL.IS", symbol: "TEHOL", name: "Tera Yatırım Teknoloji Holding", sector: "Holding"),
        Stock(id: "TRHOL.IS", symbol: "TRHOL", name: "Tera Financial Holding", sector: "Holding"),
        Stock(id: "UNLU.IS",  symbol: "UNLU",  name: "Ünlü Yatırım Holding", sector: "Holding"),
        Stock(id: "VERUS.IS", symbol: "VERUS", name: "Verusa Holding", sector: "Holding"),

        // MARK: - Hizmetler
        Stock(id: "AKYHO.IS", symbol: "AKYHO", name: "Akdeniz Yatırım Holding", sector: "Hizmetler"),
        Stock(id: "BINBN.IS", symbol: "BINBN", name: "Bin Ulaşım Teknolojileri", sector: "Hizmetler"),
        Stock(id: "EDATA.IS", symbol: "EDATA", name: "E-Data Teknoloji Pazarlama", sector: "Hizmetler"),
        Stock(id: "GATEG.IS", symbol: "GATEG", name: "Gate Group Teknoloji", sector: "Hizmetler"),
        Stock(id: "IHAAS.IS", symbol: "IHAAS", name: "İhlas Haber Ajansı", sector: "Hizmetler"),
        Stock(id: "MACKO.IS", symbol: "MACKO", name: "Mackolik İnternet", sector: "Hizmetler"),
        Stock(id: "MCARD.IS", symbol: "MCARD", name: "Metropal Kurumsal Hizmetler", sector: "Hizmetler"),
        Stock(id: "PCILT.IS", symbol: "PCILT", name: "PC İletişim Ve Medya", sector: "Hizmetler"),
        Stock(id: "PRZMA.IS", symbol: "PRZMA", name: "Prizma Pres Matbaacılık", sector: "Hizmetler"),
        Stock(id: "SKYLP.IS", symbol: "SKYLP", name: "Skyalp Finansal Teknolojiler", sector: "Hizmetler"),
        Stock(id: "SMRVA.IS", symbol: "SMRVA", name: "Sümer Varlık Yönetim", sector: "Hizmetler"),

        // MARK: - İnşaat (Ek-2)
        Stock(id: "AKFIS.IS", symbol: "AKFIS", name: "Akfen İnşaat Turizm", sector: "İnşaat"),
        Stock(id: "ANELE.IS", symbol: "ANELE", name: "Anel Elektrik Proje Taahhüt", sector: "İnşaat"),
        Stock(id: "GLRMK.IS", symbol: "GLRMK", name: "Gülermak Ağır Sanayi İnşaat", sector: "İnşaat"),
        Stock(id: "NIBAS.IS", symbol: "NIBAS", name: "Niğbaş Niğde Beton", sector: "İnşaat"),
        Stock(id: "RALYH.IS", symbol: "RALYH", name: "Ral Yatırım Holding", sector: "İnşaat"),
        Stock(id: "UCAYM.IS", symbol: "UCAYM", name: "Ucay Mühendislik Enerji", sector: "İnşaat"),
        Stock(id: "YAYLA.IS", symbol: "YAYLA", name: "Yayla Enerji Üretim Turizm İnşaat", sector: "İnşaat"),
        Stock(id: "YYAPI.IS", symbol: "YYAPI", name: "Yeşil Yapı Endüstrisi", sector: "İnşaat"),

        // MARK: - Kağıt (Ek-2)
        Stock(id: "ALKA.IS",  symbol: "ALKA",  name: "Alkim Kağıt", sector: "Kağıt"),
        Stock(id: "BARMA.IS", symbol: "BARMA", name: "Barem Ambalaj", sector: "Kağıt"),
        Stock(id: "BNTAS.IS", symbol: "BNTAS", name: "Bantaş Bandırma Ambalaj", sector: "Kağıt"),
        Stock(id: "DURDO.IS", symbol: "DURDO", name: "Duran Doğan Basım Ve Ambalaj", sector: "Kağıt"),
        Stock(id: "EMNIS.IS", symbol: "EMNIS", name: "Eminiş Ambalaj", sector: "Kağıt"),
        Stock(id: "KONKA.IS", symbol: "KONKA", name: "Konya Kağıt", sector: "Kağıt"),
        Stock(id: "MNDTR.IS", symbol: "MNDTR", name: "Mondi Turkey Ambalaj", sector: "Kağıt"),
        Stock(id: "SEKUR.IS", symbol: "SEKUR", name: "Sekuro Plastik Ambalaj", sector: "Kağıt"),

        // MARK: - Kimya (Ek-2)
        Stock(id: "BAHKM.IS", symbol: "BAHKM", name: "Bahadır Kimya", sector: "Kimya"),
        Stock(id: "EKIZ.IS",  symbol: "EKIZ",  name: "Ekiz Kimya", sector: "Kimya"),
        Stock(id: "GENKM.IS", symbol: "GENKM", name: "Gentaş Kimya", sector: "Kimya"),
        Stock(id: "KLKIM.IS", symbol: "KLKIM", name: "Kalekim Kimyevi Maddeler", sector: "Kimya"),
        Stock(id: "MERCN.IS", symbol: "MERCN", name: "Mercan Kimya", sector: "Kimya"),
        Stock(id: "TMPOL.IS", symbol: "TMPOL", name: "Temapol Polimer Plastik", sector: "Kimya"),

        // MARK: - Lojistik (Ek-2)
        Stock(id: "HOROZ.IS", symbol: "HOROZ", name: "Horoz Lojistik Kargo", sector: "Lojistik"),
        Stock(id: "HRKET.IS", symbol: "HRKET", name: "Hareket Proje Taşımacılığı", sector: "Lojistik"),
        Stock(id: "MMCAS.IS", symbol: "MMCAS", name: "MMC Sanayi Ticari Yatırımlar", sector: "Lojistik"),
        Stock(id: "PASEU.IS", symbol: "PASEU", name: "Pasifik Eurasia Lojistik", sector: "Lojistik"),
        Stock(id: "PLTUR.IS", symbol: "PLTUR", name: "Platform Turizm Taşımacılık", sector: "Lojistik"),
        Stock(id: "RYSAS.IS", symbol: "RYSAS", name: "Reysaş Taşımacılık Ve Lojistik", sector: "Lojistik"),
        Stock(id: "TLMAN.IS", symbol: "TLMAN", name: "Trabzon Liman İşletmeciliği", sector: "Lojistik"),

        // MARK: - Madencilik (Ek-2)
        Stock(id: "CVKMD.IS", symbol: "CVKMD", name: "CVK Maden İşletmeleri", sector: "Madencilik"),
        Stock(id: "MARBL.IS", symbol: "MARBL", name: "Tureks Madencilik", sector: "Madencilik"),
        Stock(id: "TRMET.IS", symbol: "TRMET", name: "TR Anadolu Metal Madencilik", sector: "Madencilik"),
        Stock(id: "VSNMD.IS", symbol: "VSNMD", name: "Visne Madencilik", sector: "Madencilik"),

        // MARK: - Metal (Ek-2)
        Stock(id: "AYES.IS",  symbol: "AYES",  name: "Ayes Çelik Hasır Ve Çit", sector: "Metal"),
        Stock(id: "BMSCH.IS", symbol: "BMSCH", name: "BMS Çelik Hasır", sector: "Metal"),
        Stock(id: "BMSTL.IS", symbol: "BMSTL", name: "BMS Birleşik Metal", sector: "Metal"),
        Stock(id: "BURVA.IS", symbol: "BURVA", name: "Burçelik Vana", sector: "Metal"),
        Stock(id: "CEMTS.IS", symbol: "CEMTS", name: "Çemtaş Çelik Makina", sector: "Metal"),
        Stock(id: "CUSAN.IS", symbol: "CUSAN", name: "Çuhadaroğlu Metal", sector: "Metal"),
        Stock(id: "ERCB.IS",  symbol: "ERCB",  name: "Erciyas Çelik Boru", sector: "Metal"),
        Stock(id: "FORMT.IS", symbol: "FORMT", name: "Formet Metal Ve Cam", sector: "Metal"),
        Stock(id: "FRMPL.IS", symbol: "FRMPL", name: "Formül Plastik Ve Metal", sector: "Metal"),
        Stock(id: "ISDMR.IS", symbol: "ISDMR", name: "İskenderun Demir Ve Çelik", sector: "Metal"),
        Stock(id: "KOCMT.IS", symbol: "KOCMT", name: "Koç Metalurji", sector: "Metal"),
        Stock(id: "KRDMA.IS", symbol: "KRDMA", name: "Kardemir Karabük Demir Çelik A", sector: "Demir-Çelik"),
        Stock(id: "TCKRC.IS", symbol: "TCKRC", name: "Kıraç Galvaniz Metal", sector: "Metal"),
        Stock(id: "TUCLK.IS", symbol: "TUCLK", name: "Tuğçelik Alüminyum", sector: "Metal"),

        // MARK: - Otomotiv (Ek-2)
        Stock(id: "BFREN.IS", symbol: "BFREN", name: "Bosch Fren Sistemleri", sector: "Otomotiv"),
        Stock(id: "FMIZP.IS", symbol: "FMIZP", name: "Federal-Mogul İzmit Piston", sector: "Otomotiv"),

        // MARK: - Perakende (Ek-2)
        Stock(id: "ARTMS.IS", symbol: "ARTMS", name: "Artemis Halı", sector: "Perakende"),
        Stock(id: "ARZUM.IS", symbol: "ARZUM", name: "Arzum Elektrikli Ev Aletleri", sector: "Perakende"),
        Stock(id: "AZTEK.IS", symbol: "AZTEK", name: "Aztek Teknoloji Ürünleri", sector: "Perakende"),
        Stock(id: "BEYAZ.IS", symbol: "BEYAZ", name: "Beyaz Filo Oto Kiralama", sector: "Perakende"),
        Stock(id: "CASA.IS",  symbol: "CASA",  name: "Casa Emtia Petrol", sector: "Perakende"),
        Stock(id: "COSMO.IS", symbol: "COSMO", name: "Cosmos Yatırım Holding", sector: "Perakende"),
        Stock(id: "DCTTR.IS", symbol: "DCTTR", name: "DCT Trading Dış Ticaret", sector: "Perakende"),
        Stock(id: "EBEBK.IS", symbol: "EBEBK", name: "Ebebek Mağazacılık", sector: "Perakende"),
        Stock(id: "GRTHO.IS", symbol: "GRTHO", name: "Grainturk Holding", sector: "Perakende"),
        Stock(id: "INGRM.IS", symbol: "INGRM", name: "Ingram Micro Bilişim", sector: "Perakende"),
        Stock(id: "KIMMR.IS", symbol: "KIMMR", name: "Ersan Alışveriş Hizmetleri", sector: "Perakende"),
        Stock(id: "LYDHO.IS", symbol: "LYDHO", name: "Lydia Holding", sector: "Perakende"),
        Stock(id: "MOPAS.IS", symbol: "MOPAS", name: "Mopas Marketcilik", sector: "Perakende"),
        Stock(id: "SUWEN.IS", symbol: "SUWEN", name: "Suwen Tekstil Pazarlama", sector: "Perakende"),
        Stock(id: "TGSAS.IS", symbol: "TGSAS", name: "TGS Dış Ticaret", sector: "Perakende"),
        Stock(id: "VANGD.IS", symbol: "VANGD", name: "Vanet Gıda", sector: "Perakende"),
        Stock(id: "YKSLN.IS", symbol: "YKSLN", name: "Yükselen Çelik", sector: "Perakende"),

        // MARK: - Sağlık (Ek-2)
        Stock(id: "ANGEN.IS", symbol: "ANGEN", name: "Anatolia Tanı Ve Biyoteknoloji", sector: "Sağlık"),
        Stock(id: "AVHOL.IS", symbol: "AVHOL", name: "Avrupa Yatırım Holding", sector: "Sağlık"),
        Stock(id: "EGEPO.IS", symbol: "EGEPO", name: "Nasmed Özel Sağlık Hizmetleri", sector: "Sağlık"),
        Stock(id: "GENIL.IS", symbol: "GENIL", name: "Gen İlaç Ve Sağlık Ürünleri", sector: "İlaç"),
        Stock(id: "KAYSE.IS", symbol: "KAYSE", name: "Kayseri Şeker Fabrikası", sector: "Gıda"),
        Stock(id: "ONCSM.IS", symbol: "ONCSM", name: "Oncosem Onkolojik Sistemler", sector: "Sağlık"),
        Stock(id: "TNZTP.IS", symbol: "TNZTP", name: "Tapdi Oksijen Özel Sağlık", sector: "Sağlık"),

        // MARK: - Savunma (Ek-2)
        Stock(id: "ALTNY.IS", symbol: "ALTNY", name: "Altınay Savunma Teknolojileri", sector: "Savunma"),
        Stock(id: "PAPIL.IS", symbol: "PAPIL", name: "Papilon Savunma Teknoloji", sector: "Savunma"),
        Stock(id: "SDTTR.IS", symbol: "SDTTR", name: "SDT Uzay Ve Savunma Teknolojileri", sector: "Savunma"),

        // MARK: - Seramik (Ek-2)
        Stock(id: "KLSER.IS", symbol: "KLSER", name: "Kaleseramik Çanakkale", sector: "Seramik"),
        Stock(id: "SERNT.IS", symbol: "SERNT", name: "Seranit Granit Seramik", sector: "Seramik"),

        // MARK: - Teknoloji (Ek-2)
        Stock(id: "AGROT.IS", symbol: "AGROT", name: "Agrotech Yüksek Teknoloji", sector: "Teknoloji"),
        Stock(id: "ATATP.IS", symbol: "ATATP", name: "ATP Yazılım Ve Teknoloji", sector: "Teknoloji"),
        Stock(id: "BINHO.IS", symbol: "BINHO", name: "1000 Yatırımlar Holding", sector: "Teknoloji"),
        Stock(id: "CWENE.IS", symbol: "CWENE", name: "CW Enerji Mühendislik", sector: "Teknoloji"),
        Stock(id: "EMPAE.IS", symbol: "EMPAE", name: "Empa Elektronik", sector: "Teknoloji"),
        Stock(id: "NETCD.IS", symbol: "NETCD", name: "Netcad Yazılım", sector: "Teknoloji"),
        Stock(id: "ODINE.IS", symbol: "ODINE", name: "Odine Solutions Teknoloji", sector: "Teknoloji"),
        Stock(id: "PATEK.IS", symbol: "PATEK", name: "Pasifik Teknoloji", sector: "Teknoloji"),
        Stock(id: "REEDR.IS", symbol: "REEDR", name: "Reeder Teknoloji", sector: "Teknoloji"),
        Stock(id: "SMART.IS", symbol: "SMART", name: "Smartiks Yazılım", sector: "Teknoloji"),

        // MARK: - Tekstil (Ek-2)
        Stock(id: "ATEKS.IS", symbol: "ATEKS", name: "Akın Tekstil", sector: "Tekstil"),
        Stock(id: "BRMEN.IS", symbol: "BRMEN", name: "Birlik Mensucat", sector: "Tekstil"),
        Stock(id: "DAGI.IS",  symbol: "DAGI",  name: "Dagi Giyim", sector: "Tekstil"),
        Stock(id: "DERIM.IS", symbol: "DERIM", name: "Derimod Konfeksiyon", sector: "Tekstil"),
        Stock(id: "DIRIT.IS", symbol: "DIRIT", name: "Diriteks Diriliş Tekstil", sector: "Tekstil"),
        Stock(id: "HATEK.IS", symbol: "HATEK", name: "Hateks Hatay Tekstil", sector: "Tekstil"),
        Stock(id: "KOTON.IS", symbol: "KOTON", name: "Koton Mağazacılık Tekstil", sector: "Tekstil"),
        Stock(id: "KRTEK.IS", symbol: "KRTEK", name: "Karsu Tekstilsanayi", sector: "Tekstil"),
        Stock(id: "RODRG.IS", symbol: "RODRG", name: "Rodrigo Tekstil", sector: "Tekstil"),
        Stock(id: "RUBNS.IS", symbol: "RUBNS", name: "Rubenis Tekstil", sector: "Tekstil"),
        Stock(id: "SONME.IS", symbol: "SONME", name: "Sönmez Filament Sentetik İplik", sector: "Tekstil"),
        Stock(id: "SUNTK.IS", symbol: "SUNTK", name: "Sun Tekstil", sector: "Tekstil"),

        // MARK: - Turizm (Ek-2)
        Stock(id: "ATATR.IS", symbol: "ATATR", name: "Ata Turizm İşletmecilik", sector: "Turizm"),
        Stock(id: "BIGCH.IS", symbol: "BIGCH", name: "Büyük Şefler Gıda Turizm", sector: "Turizm"),
        Stock(id: "BIGTK.IS", symbol: "BIGTK", name: "Big Medya Teknoloji", sector: "Turizm"),
        Stock(id: "BLUME.IS", symbol: "BLUME", name: "Blume Metal Kimya", sector: "Turizm"),
        Stock(id: "BYDNR.IS", symbol: "BYDNR", name: "Baydöner Restoranları", sector: "Turizm"),
        Stock(id: "CEOEM.IS", symbol: "CEOEM", name: "CEO Event Medya", sector: "Turizm"),
        Stock(id: "DOCO.IS",  symbol: "DOCO",  name: "Do & Co", sector: "Turizm"),
        Stock(id: "ETILR.IS", symbol: "ETILR", name: "Etiler Gıda Ve Ticari Yatırımlar", sector: "Turizm"),
        Stock(id: "GRSEL.IS", symbol: "GRSEL", name: "Gür-Sel Turizm Taşımacılık", sector: "Turizm"),
        Stock(id: "GZNMI.IS", symbol: "GZNMI", name: "Gezinomi Seyahat Turizm", sector: "Turizm"),
        Stock(id: "IHGZT.IS", symbol: "IHGZT", name: "İhlas Gazetecilik", sector: "Medya"),
        Stock(id: "KERVN.IS", symbol: "KERVN", name: "Kervansaray Yatırım Holding", sector: "Turizm"),
        Stock(id: "KSTUR.IS", symbol: "KSTUR", name: "Kuştur Kuşadası Turizm", sector: "Turizm"),
        Stock(id: "MARTI.IS", symbol: "MARTI", name: "Martı Otel İşletmeleri", sector: "Turizm"),
        Stock(id: "TABGD.IS", symbol: "TABGD", name: "TAB Gıda", sector: "Turizm"),
        Stock(id: "TEKTU.IS", symbol: "TEKTU", name: "Tek-Art İnşaat Turizm", sector: "Turizm"),
        Stock(id: "ULAS.IS",  symbol: "ULAS",  name: "Ulaşlar Turizm", sector: "Turizm"),
        Stock(id: "ZEDUR.IS", symbol: "ZEDUR", name: "Zedur Enerji Elektrik Üretim", sector: "Enerji"),

        // MARK: - Sanayi (Ek-2)
        Stock(id: "ALCAR.IS", symbol: "ALCAR", name: "Alarko Carrier", sector: "Sanayi"),
        Stock(id: "BALAT.IS", symbol: "BALAT", name: "Balatacılar Balatacılık", sector: "Sanayi"),
        Stock(id: "BIENY.IS", symbol: "BIENY", name: "Bien Yapı Ürünleri", sector: "Sanayi"),
        Stock(id: "BLCYT.IS", symbol: "BLCYT", name: "Bilici Yatırım", sector: "Sanayi"),
        Stock(id: "BRKO.IS",  symbol: "BRKO",  name: "Birko Birleşik Koyunlulular Mensucat", sector: "Tekstil"),
        Stock(id: "BRKSN.IS", symbol: "BRKSN", name: "Berkosan Yalıtım", sector: "Sanayi"),
        Stock(id: "BRLSM.IS", symbol: "BRLSM", name: "Birleşim Mühendislik", sector: "Sanayi"),
        Stock(id: "BVSAN.IS", symbol: "BVSAN", name: "Bülbüloğlu Vinç", sector: "Sanayi"),
        Stock(id: "CGCAM.IS", symbol: "CGCAM", name: "Çağdaş Cam", sector: "Cam"),
        Stock(id: "DGNMO.IS", symbol: "DGNMO", name: "Doğanlar Mobilya Grubu", sector: "Sanayi"),
        Stock(id: "DOFER.IS", symbol: "DOFER", name: "Dofer Yapı Malzemeleri", sector: "Sanayi"),
        Stock(id: "DOFRB.IS", symbol: "DOFRB", name: "DOF Robotik", sector: "Sanayi"),
        Stock(id: "DOKTA.IS", symbol: "DOKTA", name: "Döktaş Dökümcülük", sector: "Sanayi"),
        Stock(id: "EKOS.IS",  symbol: "EKOS",  name: "Ekos Teknoloji Ve Elektrik", sector: "Sanayi"),
        Stock(id: "FZLGY.IS", symbol: "FZLGY", name: "Fuzul GYO", sector: "GYO"),
        Stock(id: "GIPTA.IS", symbol: "GIPTA", name: "Gipta Ofis Kırtasiye", sector: "Sanayi"),
        Stock(id: "HATSN.IS", symbol: "HATSN", name: "Hat-San Gemi İnşaa", sector: "Sanayi"),
        Stock(id: "HKTM.IS",  symbol: "HKTM",  name: "Hidropar Hareket Kontrol", sector: "Sanayi"),
        Stock(id: "IEYHO.IS", symbol: "IEYHO", name: "Işıklar Enerji Ve Yapı Holding", sector: "Holding"),
        Stock(id: "IMASM.IS", symbol: "IMASM", name: "İmaş Makina", sector: "Sanayi"),
        Stock(id: "INTEK.IS", symbol: "INTEK", name: "Innosa Teknoloji", sector: "Teknoloji"),
        Stock(id: "ISBIR.IS", symbol: "ISBIR", name: "İşbir Holding", sector: "Holding"),
        Stock(id: "ISKPL.IS", symbol: "ISKPL", name: "Işık Plastik", sector: "Sanayi"),
        Stock(id: "ISSEN.IS", symbol: "ISSEN", name: "İşbir Sentetik Dokuma", sector: "Tekstil"),
        Stock(id: "IZFAS.IS", symbol: "IZFAS", name: "İzmir Fırça", sector: "Sanayi"),
        Stock(id: "KLSYN.IS", symbol: "KLSYN", name: "Koleksiyon Mobilya", sector: "Sanayi"),
        Stock(id: "KLYPV.IS", symbol: "KLYPV", name: "Kalyon Güneş Teknolojileri", sector: "Enerji"),
        Stock(id: "KMPUR.IS", symbol: "KMPUR", name: "Kimteks Poliüretan", sector: "Kimya"),
        Stock(id: "KOPOL.IS", symbol: "KOPOL", name: "Koza Polyester", sector: "Kimya"),
        Stock(id: "KTSKR.IS", symbol: "KTSKR", name: "Kütahya Şeker Fabrikası", sector: "Gıda"),
        Stock(id: "KUTPO.IS", symbol: "KUTPO", name: "Kütahya Porselen", sector: "Seramik"),
        Stock(id: "KUVVA.IS", symbol: "KUVVA", name: "Kuvva Gıda", sector: "Gıda"),
        Stock(id: "LMKDC.IS", symbol: "LMKDC", name: "Limak Doğu Anadolu Çimento", sector: "Çimento"),
        Stock(id: "MAKTK.IS", symbol: "MAKTK", name: "Makina Takım Endüstrisi", sector: "Sanayi"),
        Stock(id: "MEGAP.IS", symbol: "MEGAP", name: "Mega Polietilen Köpük", sector: "Kimya"),
        Stock(id: "MEKAG.IS", symbol: "MEKAG", name: "Meka Global Makine", sector: "Sanayi"),
        Stock(id: "MZHLD.IS", symbol: "MZHLD", name: "Mazhar Zorlu Holding", sector: "Holding"),
        Stock(id: "OFSYM.IS", symbol: "OFSYM", name: "Ofis Yem Gıda", sector: "Gıda"),
        Stock(id: "ORMA.IS",  symbol: "ORMA",  name: "Orma Orman Mahsulleri İntegre", sector: "Sanayi"),
        Stock(id: "OTTO.IS",  symbol: "OTTO",  name: "Otto Holding", sector: "Holding"),
        Stock(id: "OZATD.IS", symbol: "OZATD", name: "Ozata Denizcilik", sector: "Denizcilik"),
        Stock(id: "OZRDN.IS", symbol: "OZRDN", name: "Özerden Plastik", sector: "Kimya"),
        Stock(id: "OZSUB.IS", symbol: "OZSUB", name: "Özsu Balık Üretim", sector: "Gıda"),
        Stock(id: "OZYSR.IS", symbol: "OZYSR", name: "Özyasar Tel Ve Galvanizleme", sector: "Metal"),
        Stock(id: "POLTK.IS", symbol: "POLTK", name: "Politeknik Metal", sector: "Metal"),
        Stock(id: "PSDTC.IS", symbol: "PSDTC", name: "Pergamon Status Dış Ticaret", sector: "Perakende"),
        Stock(id: "QUAGR.IS", symbol: "QUAGR", name: "Qua Granit Yapı Ürünleri", sector: "Seramik"),
        Stock(id: "RNPOL.IS", symbol: "RNPOL", name: "Rainbow Polikarbonat", sector: "Kimya"),
        Stock(id: "RUZYE.IS", symbol: "RUZYE", name: "Ruzy Madencilik Ve Enerji", sector: "Madencilik"),
        Stock(id: "SAFKR.IS", symbol: "SAFKR", name: "Safkar Ege Soğutmacılık", sector: "Sanayi"),
        Stock(id: "SANEL.IS", symbol: "SANEL", name: "San-El Mühendislik Elektrik", sector: "Sanayi"),
        Stock(id: "SANFM.IS", symbol: "SANFM", name: "Sanifoam Endüstri Ürünleri", sector: "Sanayi"),
        Stock(id: "SAYAS.IS", symbol: "SAYAS", name: "Say Yenilenebilir Enerji Ekipmanları", sector: "Enerji"),
        Stock(id: "SILVR.IS", symbol: "SILVR", name: "Silverline Endüstri", sector: "Sanayi"),
        Stock(id: "SNICA.IS", symbol: "SNICA", name: "Sanica Isı", sector: "Sanayi"),
        Stock(id: "SODSN.IS", symbol: "SODSN", name: "Sodaş Sodyum Sanayii", sector: "Kimya"),
        Stock(id: "SOKE.IS",  symbol: "SOKE",  name: "Söke Değirmencilik", sector: "Gıda"),
        Stock(id: "SUMAS.IS", symbol: "SUMAS", name: "Sumaş Suni Tahta Ve Mobilya", sector: "Sanayi"),
        Stock(id: "TARKM.IS", symbol: "TARKM", name: "Tarkim Bitki Koruma", sector: "Tarım"),
        Stock(id: "TRALT.IS", symbol: "TRALT", name: "Türk Altın İşletmeleri", sector: "Madencilik"),
        Stock(id: "ULUUN.IS", symbol: "ULUUN", name: "Ulusoy Un", sector: "Gıda"),
        Stock(id: "YAPRK.IS", symbol: "YAPRK", name: "Yaprak Süt Ve Besi Çiftlikleri", sector: "Tarım"),
        Stock(id: "YBTAS.IS", symbol: "YBTAS", name: "Yibitaş İnşaat Malzemeleri", sector: "İnşaat"),
        Stock(id: "YIGIT.IS", symbol: "YIGIT", name: "Yiğit Akü Malzemeleri", sector: "Sanayi"),
        Stock(id: "YONGA.IS", symbol: "YONGA", name: "Yonga Mobilya", sector: "Sanayi"),

        // MARK: - Gıda (Ek-2)
        Stock(id: "ALKLC.IS", symbol: "ALKLC", name: "Altınkılıç Gıda", sector: "Gıda"),
        Stock(id: "ARMGD.IS", symbol: "ARMGD", name: "Armada Gıda", sector: "Gıda"),
        Stock(id: "ATAKP.IS", symbol: "ATAKP", name: "Atakey Patates Gıda", sector: "Gıda"),
        Stock(id: "AVOD.IS",  symbol: "AVOD",  name: "AVOD Kurutulmuş Gıda", sector: "Gıda"),
        Stock(id: "BALSU.IS", symbol: "BALSU", name: "Balsu Gıda", sector: "Gıda"),
        Stock(id: "BAYRK.IS", symbol: "BAYRK", name: "Bayrak EBT Taban", sector: "Gıda"),
        Stock(id: "BESLR.IS", symbol: "BESLR", name: "Besler Gıda Ve Kimya", sector: "Gıda"),
        Stock(id: "CEMZY.IS", symbol: "CEMZY", name: "Cem Zeytin", sector: "Gıda"),
        Stock(id: "DMRGD.IS", symbol: "DMRGD", name: "DMR Unlu Mamuller", sector: "Gıda"),
        Stock(id: "DURKN.IS", symbol: "DURKN", name: "Durukan Şekerleme", sector: "Gıda"),
        Stock(id: "EFOR.IS",  symbol: "EFOR",  name: "Efor Yatırım Sanayi", sector: "Gıda"),
        Stock(id: "EKSUN.IS", symbol: "EKSUN", name: "Eksun Gıda Tarım", sector: "Gıda"),
        Stock(id: "ELITE.IS", symbol: "ELITE", name: "Elite Naturel Organik Gıda", sector: "Gıda"),
        Stock(id: "ENSRI.IS", symbol: "ENSRI", name: "Ensari Deri Gıda", sector: "Gıda"),
        Stock(id: "FADE.IS",  symbol: "FADE",  name: "Fade Gıda Yatırım", sector: "Gıda"),
        Stock(id: "FRIGO.IS", symbol: "FRIGO", name: "Frigo-Pak Gıda", sector: "Gıda"),
        Stock(id: "GOKNR.IS", symbol: "GOKNR", name: "Göknur Gıda Maddeleri", sector: "Gıda"),
        Stock(id: "GUNDG.IS", symbol: "GUNDG", name: "Gündoğdu Gıda Süt Ürünleri", sector: "Gıda"),
        Stock(id: "KRPLS.IS", symbol: "KRPLS", name: "Koroplast Temizlik Ambalaj", sector: "Kimya"),
        Stock(id: "KRSTL.IS", symbol: "KRSTL", name: "Kristal Kola Ve Meşrubat", sector: "Gıda"),
        Stock(id: "LILAK.IS", symbol: "LILAK", name: "Lila Kağıt", sector: "Kağıt"),
        Stock(id: "MERKO.IS", symbol: "MERKO", name: "Merko Gıda", sector: "Gıda"),
        Stock(id: "MEYSU.IS", symbol: "MEYSU", name: "Meysu Gıda", sector: "Gıda"),
        Stock(id: "OBAMS.IS", symbol: "OBAMS", name: "Oba Makarna", sector: "Gıda"),
        Stock(id: "PENGD.IS", symbol: "PENGD", name: "Penguen Gıda", sector: "Gıda"),
        Stock(id: "PINSU.IS", symbol: "PINSU", name: "Pınar Su Ve İçecek", sector: "Gıda"),
        Stock(id: "SEGMN.IS", symbol: "SEGMN", name: "Segmen Kardeşler Gıda", sector: "Gıda"),
        Stock(id: "SELVA.IS", symbol: "SELVA", name: "Selva Gıda", sector: "Gıda"),
        Stock(id: "VKING.IS", symbol: "VKING", name: "Viking Kağıt Ve Selüloz", sector: "Kağıt"),

        Stock(id: "DERHL.IS", symbol: "DERHL", name: "Derlüks Yatırım Holding", sector: "Holding"),
        Stock(id: "DUNYH.IS", symbol: "DUNYH", name: "Dünya Holding", sector: "Holding"),
        Stock(id: "IZINV.IS", symbol: "IZINV", name: "İz Yatırım Holding", sector: "Holding"),
        Stock(id: "KLRHO.IS", symbol: "KLRHO", name: "Kiler Holding", sector: "Holding"),
        Stock(id: "LRSHO.IS", symbol: "LRSHO", name: "Loras Holding", sector: "Holding"),
        Stock(id: "LYDYE.IS", symbol: "LYDYE", name: "Lydia Yeşil Enerji", sector: "Enerji"),
        Stock(id: "DMLKT.IS", symbol: "DMLKT", name: "Emlak Konut Sertifikası", sector: "GYO"),
    ]

    // Geriye dönük uyumluluk
    static var bist100: [Stock] { all }
}
